// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/heroiclabs/nakama-common/api/api.proto
// Protobuf Java Version: 4.28.2

package com.heroiclabs.nakama.api;

/**
 * <pre>
 * Batch delete storage objects.
 * </pre>
 *
 * Protobuf type {@code nakama.api.DeleteStorageObjectsRequest}
 */
public final class DeleteStorageObjectsRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:nakama.api.DeleteStorageObjectsRequest)
    DeleteStorageObjectsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      DeleteStorageObjectsRequest.class.getName());
  }
  // Use DeleteStorageObjectsRequest.newBuilder() to construct.
  private DeleteStorageObjectsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DeleteStorageObjectsRequest() {
    objectIds_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.heroiclabs.nakama.api.ApiProto.internal_static_nakama_api_DeleteStorageObjectsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.heroiclabs.nakama.api.ApiProto.internal_static_nakama_api_DeleteStorageObjectsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.heroiclabs.nakama.api.DeleteStorageObjectsRequest.class, com.heroiclabs.nakama.api.DeleteStorageObjectsRequest.Builder.class);
  }

  public static final int OBJECT_IDS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.heroiclabs.nakama.api.DeleteStorageObjectId> objectIds_;
  /**
   * <pre>
   * Batch of storage objects.
   * </pre>
   *
   * <code>repeated .nakama.api.DeleteStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
   */
  @java.lang.Override
  public java.util.List<com.heroiclabs.nakama.api.DeleteStorageObjectId> getObjectIdsList() {
    return objectIds_;
  }
  /**
   * <pre>
   * Batch of storage objects.
   * </pre>
   *
   * <code>repeated .nakama.api.DeleteStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.heroiclabs.nakama.api.DeleteStorageObjectIdOrBuilder> 
      getObjectIdsOrBuilderList() {
    return objectIds_;
  }
  /**
   * <pre>
   * Batch of storage objects.
   * </pre>
   *
   * <code>repeated .nakama.api.DeleteStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
   */
  @java.lang.Override
  public int getObjectIdsCount() {
    return objectIds_.size();
  }
  /**
   * <pre>
   * Batch of storage objects.
   * </pre>
   *
   * <code>repeated .nakama.api.DeleteStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
   */
  @java.lang.Override
  public com.heroiclabs.nakama.api.DeleteStorageObjectId getObjectIds(int index) {
    return objectIds_.get(index);
  }
  /**
   * <pre>
   * Batch of storage objects.
   * </pre>
   *
   * <code>repeated .nakama.api.DeleteStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
   */
  @java.lang.Override
  public com.heroiclabs.nakama.api.DeleteStorageObjectIdOrBuilder getObjectIdsOrBuilder(
      int index) {
    return objectIds_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < objectIds_.size(); i++) {
      output.writeMessage(1, objectIds_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < objectIds_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, objectIds_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.heroiclabs.nakama.api.DeleteStorageObjectsRequest)) {
      return super.equals(obj);
    }
    com.heroiclabs.nakama.api.DeleteStorageObjectsRequest other = (com.heroiclabs.nakama.api.DeleteStorageObjectsRequest) obj;

    if (!getObjectIdsList()
        .equals(other.getObjectIdsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getObjectIdsCount() > 0) {
      hash = (37 * hash) + OBJECT_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getObjectIdsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.heroiclabs.nakama.api.DeleteStorageObjectsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.heroiclabs.nakama.api.DeleteStorageObjectsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.heroiclabs.nakama.api.DeleteStorageObjectsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.heroiclabs.nakama.api.DeleteStorageObjectsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.heroiclabs.nakama.api.DeleteStorageObjectsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.heroiclabs.nakama.api.DeleteStorageObjectsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.heroiclabs.nakama.api.DeleteStorageObjectsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.heroiclabs.nakama.api.DeleteStorageObjectsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.heroiclabs.nakama.api.DeleteStorageObjectsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.heroiclabs.nakama.api.DeleteStorageObjectsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.heroiclabs.nakama.api.DeleteStorageObjectsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.heroiclabs.nakama.api.DeleteStorageObjectsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.heroiclabs.nakama.api.DeleteStorageObjectsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Batch delete storage objects.
   * </pre>
   *
   * Protobuf type {@code nakama.api.DeleteStorageObjectsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nakama.api.DeleteStorageObjectsRequest)
      com.heroiclabs.nakama.api.DeleteStorageObjectsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.heroiclabs.nakama.api.ApiProto.internal_static_nakama_api_DeleteStorageObjectsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.heroiclabs.nakama.api.ApiProto.internal_static_nakama_api_DeleteStorageObjectsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.heroiclabs.nakama.api.DeleteStorageObjectsRequest.class, com.heroiclabs.nakama.api.DeleteStorageObjectsRequest.Builder.class);
    }

    // Construct using com.heroiclabs.nakama.api.DeleteStorageObjectsRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (objectIdsBuilder_ == null) {
        objectIds_ = java.util.Collections.emptyList();
      } else {
        objectIds_ = null;
        objectIdsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.heroiclabs.nakama.api.ApiProto.internal_static_nakama_api_DeleteStorageObjectsRequest_descriptor;
    }

    @java.lang.Override
    public com.heroiclabs.nakama.api.DeleteStorageObjectsRequest getDefaultInstanceForType() {
      return com.heroiclabs.nakama.api.DeleteStorageObjectsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.heroiclabs.nakama.api.DeleteStorageObjectsRequest build() {
      com.heroiclabs.nakama.api.DeleteStorageObjectsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.heroiclabs.nakama.api.DeleteStorageObjectsRequest buildPartial() {
      com.heroiclabs.nakama.api.DeleteStorageObjectsRequest result = new com.heroiclabs.nakama.api.DeleteStorageObjectsRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.heroiclabs.nakama.api.DeleteStorageObjectsRequest result) {
      if (objectIdsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          objectIds_ = java.util.Collections.unmodifiableList(objectIds_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.objectIds_ = objectIds_;
      } else {
        result.objectIds_ = objectIdsBuilder_.build();
      }
    }

    private void buildPartial0(com.heroiclabs.nakama.api.DeleteStorageObjectsRequest result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.heroiclabs.nakama.api.DeleteStorageObjectsRequest) {
        return mergeFrom((com.heroiclabs.nakama.api.DeleteStorageObjectsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.heroiclabs.nakama.api.DeleteStorageObjectsRequest other) {
      if (other == com.heroiclabs.nakama.api.DeleteStorageObjectsRequest.getDefaultInstance()) return this;
      if (objectIdsBuilder_ == null) {
        if (!other.objectIds_.isEmpty()) {
          if (objectIds_.isEmpty()) {
            objectIds_ = other.objectIds_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureObjectIdsIsMutable();
            objectIds_.addAll(other.objectIds_);
          }
          onChanged();
        }
      } else {
        if (!other.objectIds_.isEmpty()) {
          if (objectIdsBuilder_.isEmpty()) {
            objectIdsBuilder_.dispose();
            objectIdsBuilder_ = null;
            objectIds_ = other.objectIds_;
            bitField0_ = (bitField0_ & ~0x00000001);
            objectIdsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getObjectIdsFieldBuilder() : null;
          } else {
            objectIdsBuilder_.addAllMessages(other.objectIds_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.heroiclabs.nakama.api.DeleteStorageObjectId m =
                  input.readMessage(
                      com.heroiclabs.nakama.api.DeleteStorageObjectId.parser(),
                      extensionRegistry);
              if (objectIdsBuilder_ == null) {
                ensureObjectIdsIsMutable();
                objectIds_.add(m);
              } else {
                objectIdsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.heroiclabs.nakama.api.DeleteStorageObjectId> objectIds_ =
      java.util.Collections.emptyList();
    private void ensureObjectIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        objectIds_ = new java.util.ArrayList<com.heroiclabs.nakama.api.DeleteStorageObjectId>(objectIds_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.heroiclabs.nakama.api.DeleteStorageObjectId, com.heroiclabs.nakama.api.DeleteStorageObjectId.Builder, com.heroiclabs.nakama.api.DeleteStorageObjectIdOrBuilder> objectIdsBuilder_;

    /**
     * <pre>
     * Batch of storage objects.
     * </pre>
     *
     * <code>repeated .nakama.api.DeleteStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
     */
    public java.util.List<com.heroiclabs.nakama.api.DeleteStorageObjectId> getObjectIdsList() {
      if (objectIdsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(objectIds_);
      } else {
        return objectIdsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Batch of storage objects.
     * </pre>
     *
     * <code>repeated .nakama.api.DeleteStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
     */
    public int getObjectIdsCount() {
      if (objectIdsBuilder_ == null) {
        return objectIds_.size();
      } else {
        return objectIdsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Batch of storage objects.
     * </pre>
     *
     * <code>repeated .nakama.api.DeleteStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
     */
    public com.heroiclabs.nakama.api.DeleteStorageObjectId getObjectIds(int index) {
      if (objectIdsBuilder_ == null) {
        return objectIds_.get(index);
      } else {
        return objectIdsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Batch of storage objects.
     * </pre>
     *
     * <code>repeated .nakama.api.DeleteStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
     */
    public Builder setObjectIds(
        int index, com.heroiclabs.nakama.api.DeleteStorageObjectId value) {
      if (objectIdsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureObjectIdsIsMutable();
        objectIds_.set(index, value);
        onChanged();
      } else {
        objectIdsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Batch of storage objects.
     * </pre>
     *
     * <code>repeated .nakama.api.DeleteStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
     */
    public Builder setObjectIds(
        int index, com.heroiclabs.nakama.api.DeleteStorageObjectId.Builder builderForValue) {
      if (objectIdsBuilder_ == null) {
        ensureObjectIdsIsMutable();
        objectIds_.set(index, builderForValue.build());
        onChanged();
      } else {
        objectIdsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Batch of storage objects.
     * </pre>
     *
     * <code>repeated .nakama.api.DeleteStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
     */
    public Builder addObjectIds(com.heroiclabs.nakama.api.DeleteStorageObjectId value) {
      if (objectIdsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureObjectIdsIsMutable();
        objectIds_.add(value);
        onChanged();
      } else {
        objectIdsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Batch of storage objects.
     * </pre>
     *
     * <code>repeated .nakama.api.DeleteStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
     */
    public Builder addObjectIds(
        int index, com.heroiclabs.nakama.api.DeleteStorageObjectId value) {
      if (objectIdsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureObjectIdsIsMutable();
        objectIds_.add(index, value);
        onChanged();
      } else {
        objectIdsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Batch of storage objects.
     * </pre>
     *
     * <code>repeated .nakama.api.DeleteStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
     */
    public Builder addObjectIds(
        com.heroiclabs.nakama.api.DeleteStorageObjectId.Builder builderForValue) {
      if (objectIdsBuilder_ == null) {
        ensureObjectIdsIsMutable();
        objectIds_.add(builderForValue.build());
        onChanged();
      } else {
        objectIdsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Batch of storage objects.
     * </pre>
     *
     * <code>repeated .nakama.api.DeleteStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
     */
    public Builder addObjectIds(
        int index, com.heroiclabs.nakama.api.DeleteStorageObjectId.Builder builderForValue) {
      if (objectIdsBuilder_ == null) {
        ensureObjectIdsIsMutable();
        objectIds_.add(index, builderForValue.build());
        onChanged();
      } else {
        objectIdsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Batch of storage objects.
     * </pre>
     *
     * <code>repeated .nakama.api.DeleteStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
     */
    public Builder addAllObjectIds(
        java.lang.Iterable<? extends com.heroiclabs.nakama.api.DeleteStorageObjectId> values) {
      if (objectIdsBuilder_ == null) {
        ensureObjectIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, objectIds_);
        onChanged();
      } else {
        objectIdsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Batch of storage objects.
     * </pre>
     *
     * <code>repeated .nakama.api.DeleteStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
     */
    public Builder clearObjectIds() {
      if (objectIdsBuilder_ == null) {
        objectIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        objectIdsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Batch of storage objects.
     * </pre>
     *
     * <code>repeated .nakama.api.DeleteStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
     */
    public Builder removeObjectIds(int index) {
      if (objectIdsBuilder_ == null) {
        ensureObjectIdsIsMutable();
        objectIds_.remove(index);
        onChanged();
      } else {
        objectIdsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Batch of storage objects.
     * </pre>
     *
     * <code>repeated .nakama.api.DeleteStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
     */
    public com.heroiclabs.nakama.api.DeleteStorageObjectId.Builder getObjectIdsBuilder(
        int index) {
      return getObjectIdsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Batch of storage objects.
     * </pre>
     *
     * <code>repeated .nakama.api.DeleteStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
     */
    public com.heroiclabs.nakama.api.DeleteStorageObjectIdOrBuilder getObjectIdsOrBuilder(
        int index) {
      if (objectIdsBuilder_ == null) {
        return objectIds_.get(index);  } else {
        return objectIdsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Batch of storage objects.
     * </pre>
     *
     * <code>repeated .nakama.api.DeleteStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
     */
    public java.util.List<? extends com.heroiclabs.nakama.api.DeleteStorageObjectIdOrBuilder> 
         getObjectIdsOrBuilderList() {
      if (objectIdsBuilder_ != null) {
        return objectIdsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(objectIds_);
      }
    }
    /**
     * <pre>
     * Batch of storage objects.
     * </pre>
     *
     * <code>repeated .nakama.api.DeleteStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
     */
    public com.heroiclabs.nakama.api.DeleteStorageObjectId.Builder addObjectIdsBuilder() {
      return getObjectIdsFieldBuilder().addBuilder(
          com.heroiclabs.nakama.api.DeleteStorageObjectId.getDefaultInstance());
    }
    /**
     * <pre>
     * Batch of storage objects.
     * </pre>
     *
     * <code>repeated .nakama.api.DeleteStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
     */
    public com.heroiclabs.nakama.api.DeleteStorageObjectId.Builder addObjectIdsBuilder(
        int index) {
      return getObjectIdsFieldBuilder().addBuilder(
          index, com.heroiclabs.nakama.api.DeleteStorageObjectId.getDefaultInstance());
    }
    /**
     * <pre>
     * Batch of storage objects.
     * </pre>
     *
     * <code>repeated .nakama.api.DeleteStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
     */
    public java.util.List<com.heroiclabs.nakama.api.DeleteStorageObjectId.Builder> 
         getObjectIdsBuilderList() {
      return getObjectIdsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.heroiclabs.nakama.api.DeleteStorageObjectId, com.heroiclabs.nakama.api.DeleteStorageObjectId.Builder, com.heroiclabs.nakama.api.DeleteStorageObjectIdOrBuilder> 
        getObjectIdsFieldBuilder() {
      if (objectIdsBuilder_ == null) {
        objectIdsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.heroiclabs.nakama.api.DeleteStorageObjectId, com.heroiclabs.nakama.api.DeleteStorageObjectId.Builder, com.heroiclabs.nakama.api.DeleteStorageObjectIdOrBuilder>(
                objectIds_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        objectIds_ = null;
      }
      return objectIdsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:nakama.api.DeleteStorageObjectsRequest)
  }

  // @@protoc_insertion_point(class_scope:nakama.api.DeleteStorageObjectsRequest)
  private static final com.heroiclabs.nakama.api.DeleteStorageObjectsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.heroiclabs.nakama.api.DeleteStorageObjectsRequest();
  }

  public static com.heroiclabs.nakama.api.DeleteStorageObjectsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeleteStorageObjectsRequest>
      PARSER = new com.google.protobuf.AbstractParser<DeleteStorageObjectsRequest>() {
    @java.lang.Override
    public DeleteStorageObjectsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DeleteStorageObjectsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeleteStorageObjectsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.heroiclabs.nakama.api.DeleteStorageObjectsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

