// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/heroiclabs/nakama-common/api/api.proto
// Protobuf Java Version: 4.28.2

package com.heroiclabs.nakama.api;

/**
 * <pre>
 * List realtime matches.
 * </pre>
 *
 * Protobuf type {@code nakama.api.ListMatchesRequest}
 */
public final class ListMatchesRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:nakama.api.ListMatchesRequest)
    ListMatchesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      ListMatchesRequest.class.getName());
  }
  // Use ListMatchesRequest.newBuilder() to construct.
  private ListMatchesRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListMatchesRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.heroiclabs.nakama.api.ApiProto.internal_static_nakama_api_ListMatchesRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.heroiclabs.nakama.api.ApiProto.internal_static_nakama_api_ListMatchesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.heroiclabs.nakama.api.ListMatchesRequest.class, com.heroiclabs.nakama.api.ListMatchesRequest.Builder.class);
  }

  private int bitField0_;
  public static final int LIMIT_FIELD_NUMBER = 1;
  private com.google.protobuf.Int32Value limit_;
  /**
   * <pre>
   * Limit the number of returned matches.
   * </pre>
   *
   * <code>.google.protobuf.Int32Value limit = 1 [json_name = "limit"];</code>
   * @return Whether the limit field is set.
   */
  @java.lang.Override
  public boolean hasLimit() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Limit the number of returned matches.
   * </pre>
   *
   * <code>.google.protobuf.Int32Value limit = 1 [json_name = "limit"];</code>
   * @return The limit.
   */
  @java.lang.Override
  public com.google.protobuf.Int32Value getLimit() {
    return limit_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : limit_;
  }
  /**
   * <pre>
   * Limit the number of returned matches.
   * </pre>
   *
   * <code>.google.protobuf.Int32Value limit = 1 [json_name = "limit"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.Int32ValueOrBuilder getLimitOrBuilder() {
    return limit_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : limit_;
  }

  public static final int AUTHORITATIVE_FIELD_NUMBER = 2;
  private com.google.protobuf.BoolValue authoritative_;
  /**
   * <pre>
   * Authoritative or relayed matches.
   * </pre>
   *
   * <code>.google.protobuf.BoolValue authoritative = 2 [json_name = "authoritative"];</code>
   * @return Whether the authoritative field is set.
   */
  @java.lang.Override
  public boolean hasAuthoritative() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Authoritative or relayed matches.
   * </pre>
   *
   * <code>.google.protobuf.BoolValue authoritative = 2 [json_name = "authoritative"];</code>
   * @return The authoritative.
   */
  @java.lang.Override
  public com.google.protobuf.BoolValue getAuthoritative() {
    return authoritative_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : authoritative_;
  }
  /**
   * <pre>
   * Authoritative or relayed matches.
   * </pre>
   *
   * <code>.google.protobuf.BoolValue authoritative = 2 [json_name = "authoritative"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.BoolValueOrBuilder getAuthoritativeOrBuilder() {
    return authoritative_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : authoritative_;
  }

  public static final int LABEL_FIELD_NUMBER = 3;
  private com.google.protobuf.StringValue label_;
  /**
   * <pre>
   * Label filter.
   * </pre>
   *
   * <code>.google.protobuf.StringValue label = 3 [json_name = "label"];</code>
   * @return Whether the label field is set.
   */
  @java.lang.Override
  public boolean hasLabel() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * Label filter.
   * </pre>
   *
   * <code>.google.protobuf.StringValue label = 3 [json_name = "label"];</code>
   * @return The label.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getLabel() {
    return label_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : label_;
  }
  /**
   * <pre>
   * Label filter.
   * </pre>
   *
   * <code>.google.protobuf.StringValue label = 3 [json_name = "label"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getLabelOrBuilder() {
    return label_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : label_;
  }

  public static final int MIN_SIZE_FIELD_NUMBER = 4;
  private com.google.protobuf.Int32Value minSize_;
  /**
   * <pre>
   * Minimum user count.
   * </pre>
   *
   * <code>.google.protobuf.Int32Value min_size = 4 [json_name = "minSize"];</code>
   * @return Whether the minSize field is set.
   */
  @java.lang.Override
  public boolean hasMinSize() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * Minimum user count.
   * </pre>
   *
   * <code>.google.protobuf.Int32Value min_size = 4 [json_name = "minSize"];</code>
   * @return The minSize.
   */
  @java.lang.Override
  public com.google.protobuf.Int32Value getMinSize() {
    return minSize_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : minSize_;
  }
  /**
   * <pre>
   * Minimum user count.
   * </pre>
   *
   * <code>.google.protobuf.Int32Value min_size = 4 [json_name = "minSize"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.Int32ValueOrBuilder getMinSizeOrBuilder() {
    return minSize_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : minSize_;
  }

  public static final int MAX_SIZE_FIELD_NUMBER = 5;
  private com.google.protobuf.Int32Value maxSize_;
  /**
   * <pre>
   * Maximum user count.
   * </pre>
   *
   * <code>.google.protobuf.Int32Value max_size = 5 [json_name = "maxSize"];</code>
   * @return Whether the maxSize field is set.
   */
  @java.lang.Override
  public boolean hasMaxSize() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <pre>
   * Maximum user count.
   * </pre>
   *
   * <code>.google.protobuf.Int32Value max_size = 5 [json_name = "maxSize"];</code>
   * @return The maxSize.
   */
  @java.lang.Override
  public com.google.protobuf.Int32Value getMaxSize() {
    return maxSize_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : maxSize_;
  }
  /**
   * <pre>
   * Maximum user count.
   * </pre>
   *
   * <code>.google.protobuf.Int32Value max_size = 5 [json_name = "maxSize"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.Int32ValueOrBuilder getMaxSizeOrBuilder() {
    return maxSize_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : maxSize_;
  }

  public static final int QUERY_FIELD_NUMBER = 6;
  private com.google.protobuf.StringValue query_;
  /**
   * <pre>
   * Arbitrary label query.
   * </pre>
   *
   * <code>.google.protobuf.StringValue query = 6 [json_name = "query"];</code>
   * @return Whether the query field is set.
   */
  @java.lang.Override
  public boolean hasQuery() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <pre>
   * Arbitrary label query.
   * </pre>
   *
   * <code>.google.protobuf.StringValue query = 6 [json_name = "query"];</code>
   * @return The query.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getQuery() {
    return query_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : query_;
  }
  /**
   * <pre>
   * Arbitrary label query.
   * </pre>
   *
   * <code>.google.protobuf.StringValue query = 6 [json_name = "query"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getQueryOrBuilder() {
    return query_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : query_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getLimit());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getAuthoritative());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getLabel());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(4, getMinSize());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(5, getMaxSize());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeMessage(6, getQuery());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLimit());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAuthoritative());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getLabel());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getMinSize());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getMaxSize());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getQuery());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.heroiclabs.nakama.api.ListMatchesRequest)) {
      return super.equals(obj);
    }
    com.heroiclabs.nakama.api.ListMatchesRequest other = (com.heroiclabs.nakama.api.ListMatchesRequest) obj;

    if (hasLimit() != other.hasLimit()) return false;
    if (hasLimit()) {
      if (!getLimit()
          .equals(other.getLimit())) return false;
    }
    if (hasAuthoritative() != other.hasAuthoritative()) return false;
    if (hasAuthoritative()) {
      if (!getAuthoritative()
          .equals(other.getAuthoritative())) return false;
    }
    if (hasLabel() != other.hasLabel()) return false;
    if (hasLabel()) {
      if (!getLabel()
          .equals(other.getLabel())) return false;
    }
    if (hasMinSize() != other.hasMinSize()) return false;
    if (hasMinSize()) {
      if (!getMinSize()
          .equals(other.getMinSize())) return false;
    }
    if (hasMaxSize() != other.hasMaxSize()) return false;
    if (hasMaxSize()) {
      if (!getMaxSize()
          .equals(other.getMaxSize())) return false;
    }
    if (hasQuery() != other.hasQuery()) return false;
    if (hasQuery()) {
      if (!getQuery()
          .equals(other.getQuery())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLimit()) {
      hash = (37 * hash) + LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getLimit().hashCode();
    }
    if (hasAuthoritative()) {
      hash = (37 * hash) + AUTHORITATIVE_FIELD_NUMBER;
      hash = (53 * hash) + getAuthoritative().hashCode();
    }
    if (hasLabel()) {
      hash = (37 * hash) + LABEL_FIELD_NUMBER;
      hash = (53 * hash) + getLabel().hashCode();
    }
    if (hasMinSize()) {
      hash = (37 * hash) + MIN_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getMinSize().hashCode();
    }
    if (hasMaxSize()) {
      hash = (37 * hash) + MAX_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getMaxSize().hashCode();
    }
    if (hasQuery()) {
      hash = (37 * hash) + QUERY_FIELD_NUMBER;
      hash = (53 * hash) + getQuery().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.heroiclabs.nakama.api.ListMatchesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.heroiclabs.nakama.api.ListMatchesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.heroiclabs.nakama.api.ListMatchesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.heroiclabs.nakama.api.ListMatchesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.heroiclabs.nakama.api.ListMatchesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.heroiclabs.nakama.api.ListMatchesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.heroiclabs.nakama.api.ListMatchesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.heroiclabs.nakama.api.ListMatchesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.heroiclabs.nakama.api.ListMatchesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.heroiclabs.nakama.api.ListMatchesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.heroiclabs.nakama.api.ListMatchesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.heroiclabs.nakama.api.ListMatchesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.heroiclabs.nakama.api.ListMatchesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * List realtime matches.
   * </pre>
   *
   * Protobuf type {@code nakama.api.ListMatchesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nakama.api.ListMatchesRequest)
      com.heroiclabs.nakama.api.ListMatchesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.heroiclabs.nakama.api.ApiProto.internal_static_nakama_api_ListMatchesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.heroiclabs.nakama.api.ApiProto.internal_static_nakama_api_ListMatchesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.heroiclabs.nakama.api.ListMatchesRequest.class, com.heroiclabs.nakama.api.ListMatchesRequest.Builder.class);
    }

    // Construct using com.heroiclabs.nakama.api.ListMatchesRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getLimitFieldBuilder();
        getAuthoritativeFieldBuilder();
        getLabelFieldBuilder();
        getMinSizeFieldBuilder();
        getMaxSizeFieldBuilder();
        getQueryFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      limit_ = null;
      if (limitBuilder_ != null) {
        limitBuilder_.dispose();
        limitBuilder_ = null;
      }
      authoritative_ = null;
      if (authoritativeBuilder_ != null) {
        authoritativeBuilder_.dispose();
        authoritativeBuilder_ = null;
      }
      label_ = null;
      if (labelBuilder_ != null) {
        labelBuilder_.dispose();
        labelBuilder_ = null;
      }
      minSize_ = null;
      if (minSizeBuilder_ != null) {
        minSizeBuilder_.dispose();
        minSizeBuilder_ = null;
      }
      maxSize_ = null;
      if (maxSizeBuilder_ != null) {
        maxSizeBuilder_.dispose();
        maxSizeBuilder_ = null;
      }
      query_ = null;
      if (queryBuilder_ != null) {
        queryBuilder_.dispose();
        queryBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.heroiclabs.nakama.api.ApiProto.internal_static_nakama_api_ListMatchesRequest_descriptor;
    }

    @java.lang.Override
    public com.heroiclabs.nakama.api.ListMatchesRequest getDefaultInstanceForType() {
      return com.heroiclabs.nakama.api.ListMatchesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.heroiclabs.nakama.api.ListMatchesRequest build() {
      com.heroiclabs.nakama.api.ListMatchesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.heroiclabs.nakama.api.ListMatchesRequest buildPartial() {
      com.heroiclabs.nakama.api.ListMatchesRequest result = new com.heroiclabs.nakama.api.ListMatchesRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.heroiclabs.nakama.api.ListMatchesRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.limit_ = limitBuilder_ == null
            ? limit_
            : limitBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.authoritative_ = authoritativeBuilder_ == null
            ? authoritative_
            : authoritativeBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.label_ = labelBuilder_ == null
            ? label_
            : labelBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.minSize_ = minSizeBuilder_ == null
            ? minSize_
            : minSizeBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.maxSize_ = maxSizeBuilder_ == null
            ? maxSize_
            : maxSizeBuilder_.build();
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.query_ = queryBuilder_ == null
            ? query_
            : queryBuilder_.build();
        to_bitField0_ |= 0x00000020;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.heroiclabs.nakama.api.ListMatchesRequest) {
        return mergeFrom((com.heroiclabs.nakama.api.ListMatchesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.heroiclabs.nakama.api.ListMatchesRequest other) {
      if (other == com.heroiclabs.nakama.api.ListMatchesRequest.getDefaultInstance()) return this;
      if (other.hasLimit()) {
        mergeLimit(other.getLimit());
      }
      if (other.hasAuthoritative()) {
        mergeAuthoritative(other.getAuthoritative());
      }
      if (other.hasLabel()) {
        mergeLabel(other.getLabel());
      }
      if (other.hasMinSize()) {
        mergeMinSize(other.getMinSize());
      }
      if (other.hasMaxSize()) {
        mergeMaxSize(other.getMaxSize());
      }
      if (other.hasQuery()) {
        mergeQuery(other.getQuery());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getLimitFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getAuthoritativeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getLabelFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getMinSizeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getMaxSizeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getQueryFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Int32Value limit_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> limitBuilder_;
    /**
     * <pre>
     * Limit the number of returned matches.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value limit = 1 [json_name = "limit"];</code>
     * @return Whether the limit field is set.
     */
    public boolean hasLimit() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Limit the number of returned matches.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value limit = 1 [json_name = "limit"];</code>
     * @return The limit.
     */
    public com.google.protobuf.Int32Value getLimit() {
      if (limitBuilder_ == null) {
        return limit_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : limit_;
      } else {
        return limitBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Limit the number of returned matches.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value limit = 1 [json_name = "limit"];</code>
     */
    public Builder setLimit(com.google.protobuf.Int32Value value) {
      if (limitBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        limit_ = value;
      } else {
        limitBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Limit the number of returned matches.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value limit = 1 [json_name = "limit"];</code>
     */
    public Builder setLimit(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (limitBuilder_ == null) {
        limit_ = builderForValue.build();
      } else {
        limitBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Limit the number of returned matches.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value limit = 1 [json_name = "limit"];</code>
     */
    public Builder mergeLimit(com.google.protobuf.Int32Value value) {
      if (limitBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          limit_ != null &&
          limit_ != com.google.protobuf.Int32Value.getDefaultInstance()) {
          getLimitBuilder().mergeFrom(value);
        } else {
          limit_ = value;
        }
      } else {
        limitBuilder_.mergeFrom(value);
      }
      if (limit_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Limit the number of returned matches.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value limit = 1 [json_name = "limit"];</code>
     */
    public Builder clearLimit() {
      bitField0_ = (bitField0_ & ~0x00000001);
      limit_ = null;
      if (limitBuilder_ != null) {
        limitBuilder_.dispose();
        limitBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Limit the number of returned matches.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value limit = 1 [json_name = "limit"];</code>
     */
    public com.google.protobuf.Int32Value.Builder getLimitBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getLimitFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Limit the number of returned matches.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value limit = 1 [json_name = "limit"];</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getLimitOrBuilder() {
      if (limitBuilder_ != null) {
        return limitBuilder_.getMessageOrBuilder();
      } else {
        return limit_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : limit_;
      }
    }
    /**
     * <pre>
     * Limit the number of returned matches.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value limit = 1 [json_name = "limit"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getLimitFieldBuilder() {
      if (limitBuilder_ == null) {
        limitBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getLimit(),
                getParentForChildren(),
                isClean());
        limit_ = null;
      }
      return limitBuilder_;
    }

    private com.google.protobuf.BoolValue authoritative_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> authoritativeBuilder_;
    /**
     * <pre>
     * Authoritative or relayed matches.
     * </pre>
     *
     * <code>.google.protobuf.BoolValue authoritative = 2 [json_name = "authoritative"];</code>
     * @return Whether the authoritative field is set.
     */
    public boolean hasAuthoritative() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Authoritative or relayed matches.
     * </pre>
     *
     * <code>.google.protobuf.BoolValue authoritative = 2 [json_name = "authoritative"];</code>
     * @return The authoritative.
     */
    public com.google.protobuf.BoolValue getAuthoritative() {
      if (authoritativeBuilder_ == null) {
        return authoritative_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : authoritative_;
      } else {
        return authoritativeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Authoritative or relayed matches.
     * </pre>
     *
     * <code>.google.protobuf.BoolValue authoritative = 2 [json_name = "authoritative"];</code>
     */
    public Builder setAuthoritative(com.google.protobuf.BoolValue value) {
      if (authoritativeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        authoritative_ = value;
      } else {
        authoritativeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Authoritative or relayed matches.
     * </pre>
     *
     * <code>.google.protobuf.BoolValue authoritative = 2 [json_name = "authoritative"];</code>
     */
    public Builder setAuthoritative(
        com.google.protobuf.BoolValue.Builder builderForValue) {
      if (authoritativeBuilder_ == null) {
        authoritative_ = builderForValue.build();
      } else {
        authoritativeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Authoritative or relayed matches.
     * </pre>
     *
     * <code>.google.protobuf.BoolValue authoritative = 2 [json_name = "authoritative"];</code>
     */
    public Builder mergeAuthoritative(com.google.protobuf.BoolValue value) {
      if (authoritativeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          authoritative_ != null &&
          authoritative_ != com.google.protobuf.BoolValue.getDefaultInstance()) {
          getAuthoritativeBuilder().mergeFrom(value);
        } else {
          authoritative_ = value;
        }
      } else {
        authoritativeBuilder_.mergeFrom(value);
      }
      if (authoritative_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Authoritative or relayed matches.
     * </pre>
     *
     * <code>.google.protobuf.BoolValue authoritative = 2 [json_name = "authoritative"];</code>
     */
    public Builder clearAuthoritative() {
      bitField0_ = (bitField0_ & ~0x00000002);
      authoritative_ = null;
      if (authoritativeBuilder_ != null) {
        authoritativeBuilder_.dispose();
        authoritativeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Authoritative or relayed matches.
     * </pre>
     *
     * <code>.google.protobuf.BoolValue authoritative = 2 [json_name = "authoritative"];</code>
     */
    public com.google.protobuf.BoolValue.Builder getAuthoritativeBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getAuthoritativeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Authoritative or relayed matches.
     * </pre>
     *
     * <code>.google.protobuf.BoolValue authoritative = 2 [json_name = "authoritative"];</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getAuthoritativeOrBuilder() {
      if (authoritativeBuilder_ != null) {
        return authoritativeBuilder_.getMessageOrBuilder();
      } else {
        return authoritative_ == null ?
            com.google.protobuf.BoolValue.getDefaultInstance() : authoritative_;
      }
    }
    /**
     * <pre>
     * Authoritative or relayed matches.
     * </pre>
     *
     * <code>.google.protobuf.BoolValue authoritative = 2 [json_name = "authoritative"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
        getAuthoritativeFieldBuilder() {
      if (authoritativeBuilder_ == null) {
        authoritativeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                getAuthoritative(),
                getParentForChildren(),
                isClean());
        authoritative_ = null;
      }
      return authoritativeBuilder_;
    }

    private com.google.protobuf.StringValue label_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> labelBuilder_;
    /**
     * <pre>
     * Label filter.
     * </pre>
     *
     * <code>.google.protobuf.StringValue label = 3 [json_name = "label"];</code>
     * @return Whether the label field is set.
     */
    public boolean hasLabel() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Label filter.
     * </pre>
     *
     * <code>.google.protobuf.StringValue label = 3 [json_name = "label"];</code>
     * @return The label.
     */
    public com.google.protobuf.StringValue getLabel() {
      if (labelBuilder_ == null) {
        return label_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : label_;
      } else {
        return labelBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Label filter.
     * </pre>
     *
     * <code>.google.protobuf.StringValue label = 3 [json_name = "label"];</code>
     */
    public Builder setLabel(com.google.protobuf.StringValue value) {
      if (labelBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        label_ = value;
      } else {
        labelBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Label filter.
     * </pre>
     *
     * <code>.google.protobuf.StringValue label = 3 [json_name = "label"];</code>
     */
    public Builder setLabel(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (labelBuilder_ == null) {
        label_ = builderForValue.build();
      } else {
        labelBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Label filter.
     * </pre>
     *
     * <code>.google.protobuf.StringValue label = 3 [json_name = "label"];</code>
     */
    public Builder mergeLabel(com.google.protobuf.StringValue value) {
      if (labelBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          label_ != null &&
          label_ != com.google.protobuf.StringValue.getDefaultInstance()) {
          getLabelBuilder().mergeFrom(value);
        } else {
          label_ = value;
        }
      } else {
        labelBuilder_.mergeFrom(value);
      }
      if (label_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Label filter.
     * </pre>
     *
     * <code>.google.protobuf.StringValue label = 3 [json_name = "label"];</code>
     */
    public Builder clearLabel() {
      bitField0_ = (bitField0_ & ~0x00000004);
      label_ = null;
      if (labelBuilder_ != null) {
        labelBuilder_.dispose();
        labelBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Label filter.
     * </pre>
     *
     * <code>.google.protobuf.StringValue label = 3 [json_name = "label"];</code>
     */
    public com.google.protobuf.StringValue.Builder getLabelBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getLabelFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Label filter.
     * </pre>
     *
     * <code>.google.protobuf.StringValue label = 3 [json_name = "label"];</code>
     */
    public com.google.protobuf.StringValueOrBuilder getLabelOrBuilder() {
      if (labelBuilder_ != null) {
        return labelBuilder_.getMessageOrBuilder();
      } else {
        return label_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : label_;
      }
    }
    /**
     * <pre>
     * Label filter.
     * </pre>
     *
     * <code>.google.protobuf.StringValue label = 3 [json_name = "label"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getLabelFieldBuilder() {
      if (labelBuilder_ == null) {
        labelBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getLabel(),
                getParentForChildren(),
                isClean());
        label_ = null;
      }
      return labelBuilder_;
    }

    private com.google.protobuf.Int32Value minSize_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> minSizeBuilder_;
    /**
     * <pre>
     * Minimum user count.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value min_size = 4 [json_name = "minSize"];</code>
     * @return Whether the minSize field is set.
     */
    public boolean hasMinSize() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Minimum user count.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value min_size = 4 [json_name = "minSize"];</code>
     * @return The minSize.
     */
    public com.google.protobuf.Int32Value getMinSize() {
      if (minSizeBuilder_ == null) {
        return minSize_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : minSize_;
      } else {
        return minSizeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Minimum user count.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value min_size = 4 [json_name = "minSize"];</code>
     */
    public Builder setMinSize(com.google.protobuf.Int32Value value) {
      if (minSizeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        minSize_ = value;
      } else {
        minSizeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Minimum user count.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value min_size = 4 [json_name = "minSize"];</code>
     */
    public Builder setMinSize(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (minSizeBuilder_ == null) {
        minSize_ = builderForValue.build();
      } else {
        minSizeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Minimum user count.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value min_size = 4 [json_name = "minSize"];</code>
     */
    public Builder mergeMinSize(com.google.protobuf.Int32Value value) {
      if (minSizeBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          minSize_ != null &&
          minSize_ != com.google.protobuf.Int32Value.getDefaultInstance()) {
          getMinSizeBuilder().mergeFrom(value);
        } else {
          minSize_ = value;
        }
      } else {
        minSizeBuilder_.mergeFrom(value);
      }
      if (minSize_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Minimum user count.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value min_size = 4 [json_name = "minSize"];</code>
     */
    public Builder clearMinSize() {
      bitField0_ = (bitField0_ & ~0x00000008);
      minSize_ = null;
      if (minSizeBuilder_ != null) {
        minSizeBuilder_.dispose();
        minSizeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Minimum user count.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value min_size = 4 [json_name = "minSize"];</code>
     */
    public com.google.protobuf.Int32Value.Builder getMinSizeBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getMinSizeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Minimum user count.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value min_size = 4 [json_name = "minSize"];</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getMinSizeOrBuilder() {
      if (minSizeBuilder_ != null) {
        return minSizeBuilder_.getMessageOrBuilder();
      } else {
        return minSize_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : minSize_;
      }
    }
    /**
     * <pre>
     * Minimum user count.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value min_size = 4 [json_name = "minSize"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getMinSizeFieldBuilder() {
      if (minSizeBuilder_ == null) {
        minSizeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getMinSize(),
                getParentForChildren(),
                isClean());
        minSize_ = null;
      }
      return minSizeBuilder_;
    }

    private com.google.protobuf.Int32Value maxSize_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> maxSizeBuilder_;
    /**
     * <pre>
     * Maximum user count.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value max_size = 5 [json_name = "maxSize"];</code>
     * @return Whether the maxSize field is set.
     */
    public boolean hasMaxSize() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Maximum user count.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value max_size = 5 [json_name = "maxSize"];</code>
     * @return The maxSize.
     */
    public com.google.protobuf.Int32Value getMaxSize() {
      if (maxSizeBuilder_ == null) {
        return maxSize_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : maxSize_;
      } else {
        return maxSizeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Maximum user count.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value max_size = 5 [json_name = "maxSize"];</code>
     */
    public Builder setMaxSize(com.google.protobuf.Int32Value value) {
      if (maxSizeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        maxSize_ = value;
      } else {
        maxSizeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Maximum user count.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value max_size = 5 [json_name = "maxSize"];</code>
     */
    public Builder setMaxSize(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (maxSizeBuilder_ == null) {
        maxSize_ = builderForValue.build();
      } else {
        maxSizeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Maximum user count.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value max_size = 5 [json_name = "maxSize"];</code>
     */
    public Builder mergeMaxSize(com.google.protobuf.Int32Value value) {
      if (maxSizeBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          maxSize_ != null &&
          maxSize_ != com.google.protobuf.Int32Value.getDefaultInstance()) {
          getMaxSizeBuilder().mergeFrom(value);
        } else {
          maxSize_ = value;
        }
      } else {
        maxSizeBuilder_.mergeFrom(value);
      }
      if (maxSize_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Maximum user count.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value max_size = 5 [json_name = "maxSize"];</code>
     */
    public Builder clearMaxSize() {
      bitField0_ = (bitField0_ & ~0x00000010);
      maxSize_ = null;
      if (maxSizeBuilder_ != null) {
        maxSizeBuilder_.dispose();
        maxSizeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Maximum user count.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value max_size = 5 [json_name = "maxSize"];</code>
     */
    public com.google.protobuf.Int32Value.Builder getMaxSizeBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getMaxSizeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Maximum user count.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value max_size = 5 [json_name = "maxSize"];</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getMaxSizeOrBuilder() {
      if (maxSizeBuilder_ != null) {
        return maxSizeBuilder_.getMessageOrBuilder();
      } else {
        return maxSize_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : maxSize_;
      }
    }
    /**
     * <pre>
     * Maximum user count.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value max_size = 5 [json_name = "maxSize"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getMaxSizeFieldBuilder() {
      if (maxSizeBuilder_ == null) {
        maxSizeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getMaxSize(),
                getParentForChildren(),
                isClean());
        maxSize_ = null;
      }
      return maxSizeBuilder_;
    }

    private com.google.protobuf.StringValue query_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> queryBuilder_;
    /**
     * <pre>
     * Arbitrary label query.
     * </pre>
     *
     * <code>.google.protobuf.StringValue query = 6 [json_name = "query"];</code>
     * @return Whether the query field is set.
     */
    public boolean hasQuery() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * Arbitrary label query.
     * </pre>
     *
     * <code>.google.protobuf.StringValue query = 6 [json_name = "query"];</code>
     * @return The query.
     */
    public com.google.protobuf.StringValue getQuery() {
      if (queryBuilder_ == null) {
        return query_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : query_;
      } else {
        return queryBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Arbitrary label query.
     * </pre>
     *
     * <code>.google.protobuf.StringValue query = 6 [json_name = "query"];</code>
     */
    public Builder setQuery(com.google.protobuf.StringValue value) {
      if (queryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        query_ = value;
      } else {
        queryBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Arbitrary label query.
     * </pre>
     *
     * <code>.google.protobuf.StringValue query = 6 [json_name = "query"];</code>
     */
    public Builder setQuery(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (queryBuilder_ == null) {
        query_ = builderForValue.build();
      } else {
        queryBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Arbitrary label query.
     * </pre>
     *
     * <code>.google.protobuf.StringValue query = 6 [json_name = "query"];</code>
     */
    public Builder mergeQuery(com.google.protobuf.StringValue value) {
      if (queryBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          query_ != null &&
          query_ != com.google.protobuf.StringValue.getDefaultInstance()) {
          getQueryBuilder().mergeFrom(value);
        } else {
          query_ = value;
        }
      } else {
        queryBuilder_.mergeFrom(value);
      }
      if (query_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Arbitrary label query.
     * </pre>
     *
     * <code>.google.protobuf.StringValue query = 6 [json_name = "query"];</code>
     */
    public Builder clearQuery() {
      bitField0_ = (bitField0_ & ~0x00000020);
      query_ = null;
      if (queryBuilder_ != null) {
        queryBuilder_.dispose();
        queryBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Arbitrary label query.
     * </pre>
     *
     * <code>.google.protobuf.StringValue query = 6 [json_name = "query"];</code>
     */
    public com.google.protobuf.StringValue.Builder getQueryBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getQueryFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Arbitrary label query.
     * </pre>
     *
     * <code>.google.protobuf.StringValue query = 6 [json_name = "query"];</code>
     */
    public com.google.protobuf.StringValueOrBuilder getQueryOrBuilder() {
      if (queryBuilder_ != null) {
        return queryBuilder_.getMessageOrBuilder();
      } else {
        return query_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : query_;
      }
    }
    /**
     * <pre>
     * Arbitrary label query.
     * </pre>
     *
     * <code>.google.protobuf.StringValue query = 6 [json_name = "query"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getQueryFieldBuilder() {
      if (queryBuilder_ == null) {
        queryBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getQuery(),
                getParentForChildren(),
                isClean());
        query_ = null;
      }
      return queryBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:nakama.api.ListMatchesRequest)
  }

  // @@protoc_insertion_point(class_scope:nakama.api.ListMatchesRequest)
  private static final com.heroiclabs.nakama.api.ListMatchesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.heroiclabs.nakama.api.ListMatchesRequest();
  }

  public static com.heroiclabs.nakama.api.ListMatchesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListMatchesRequest>
      PARSER = new com.google.protobuf.AbstractParser<ListMatchesRequest>() {
    @java.lang.Override
    public ListMatchesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListMatchesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListMatchesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.heroiclabs.nakama.api.ListMatchesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

