// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/heroiclabs/nakama-common/api/api.proto
// Protobuf Java Version: 4.28.2

package com.heroiclabs.nakama.api;

public interface ListLeaderboardRecordsAroundOwnerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nakama.api.ListLeaderboardRecordsAroundOwnerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The ID of the tournament to list for.
   * </pre>
   *
   * <code>string leaderboard_id = 1 [json_name = "leaderboardId"];</code>
   * @return The leaderboardId.
   */
  java.lang.String getLeaderboardId();
  /**
   * <pre>
   * The ID of the tournament to list for.
   * </pre>
   *
   * <code>string leaderboard_id = 1 [json_name = "leaderboardId"];</code>
   * @return The bytes for leaderboardId.
   */
  com.google.protobuf.ByteString
      getLeaderboardIdBytes();

  /**
   * <pre>
   * Max number of records to return. Between 1 and 100.
   * </pre>
   *
   * <code>.google.protobuf.UInt32Value limit = 2 [json_name = "limit"];</code>
   * @return Whether the limit field is set.
   */
  boolean hasLimit();
  /**
   * <pre>
   * Max number of records to return. Between 1 and 100.
   * </pre>
   *
   * <code>.google.protobuf.UInt32Value limit = 2 [json_name = "limit"];</code>
   * @return The limit.
   */
  com.google.protobuf.UInt32Value getLimit();
  /**
   * <pre>
   * Max number of records to return. Between 1 and 100.
   * </pre>
   *
   * <code>.google.protobuf.UInt32Value limit = 2 [json_name = "limit"];</code>
   */
  com.google.protobuf.UInt32ValueOrBuilder getLimitOrBuilder();

  /**
   * <pre>
   * The owner to retrieve records around.
   * </pre>
   *
   * <code>string owner_id = 3 [json_name = "ownerId"];</code>
   * @return The ownerId.
   */
  java.lang.String getOwnerId();
  /**
   * <pre>
   * The owner to retrieve records around.
   * </pre>
   *
   * <code>string owner_id = 3 [json_name = "ownerId"];</code>
   * @return The bytes for ownerId.
   */
  com.google.protobuf.ByteString
      getOwnerIdBytes();

  /**
   * <pre>
   * Expiry in seconds (since epoch) to begin fetching records from.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value expiry = 4 [json_name = "expiry"];</code>
   * @return Whether the expiry field is set.
   */
  boolean hasExpiry();
  /**
   * <pre>
   * Expiry in seconds (since epoch) to begin fetching records from.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value expiry = 4 [json_name = "expiry"];</code>
   * @return The expiry.
   */
  com.google.protobuf.Int64Value getExpiry();
  /**
   * <pre>
   * Expiry in seconds (since epoch) to begin fetching records from.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value expiry = 4 [json_name = "expiry"];</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getExpiryOrBuilder();

  /**
   * <pre>
   * A next or previous page cursor.
   * </pre>
   *
   * <code>string cursor = 5 [json_name = "cursor"];</code>
   * @return The cursor.
   */
  java.lang.String getCursor();
  /**
   * <pre>
   * A next or previous page cursor.
   * </pre>
   *
   * <code>string cursor = 5 [json_name = "cursor"];</code>
   * @return The bytes for cursor.
   */
  com.google.protobuf.ByteString
      getCursorBytes();
}
