// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/heroiclabs/nakama-common/api/api.proto
// Protobuf Java Version: 4.28.2

package com.heroiclabs.nakama.api;

public interface MatchmakerCompletionStatsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nakama.api.MatchmakerCompletionStats)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp create_time = 1 [json_name = "createTime"];</code>
   * @return Whether the createTime field is set.
   */
  boolean hasCreateTime();
  /**
   * <code>.google.protobuf.Timestamp create_time = 1 [json_name = "createTime"];</code>
   * @return The createTime.
   */
  com.google.protobuf.Timestamp getCreateTime();
  /**
   * <code>.google.protobuf.Timestamp create_time = 1 [json_name = "createTime"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp complete_time = 2 [json_name = "completeTime"];</code>
   * @return Whether the completeTime field is set.
   */
  boolean hasCompleteTime();
  /**
   * <code>.google.protobuf.Timestamp complete_time = 2 [json_name = "completeTime"];</code>
   * @return The completeTime.
   */
  com.google.protobuf.Timestamp getCompleteTime();
  /**
   * <code>.google.protobuf.Timestamp complete_time = 2 [json_name = "completeTime"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getCompleteTimeOrBuilder();
}
