// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/heroiclabs/nakama-common/api/api.proto
// Protobuf Java Version: 4.28.2

package com.heroiclabs.nakama.api;

public interface ReadStorageObjectsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nakama.api.ReadStorageObjectsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Batch of storage objects.
   * </pre>
   *
   * <code>repeated .nakama.api.ReadStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
   */
  java.util.List<com.heroiclabs.nakama.api.ReadStorageObjectId> 
      getObjectIdsList();
  /**
   * <pre>
   * Batch of storage objects.
   * </pre>
   *
   * <code>repeated .nakama.api.ReadStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
   */
  com.heroiclabs.nakama.api.ReadStorageObjectId getObjectIds(int index);
  /**
   * <pre>
   * Batch of storage objects.
   * </pre>
   *
   * <code>repeated .nakama.api.ReadStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
   */
  int getObjectIdsCount();
  /**
   * <pre>
   * Batch of storage objects.
   * </pre>
   *
   * <code>repeated .nakama.api.ReadStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
   */
  java.util.List<? extends com.heroiclabs.nakama.api.ReadStorageObjectIdOrBuilder> 
      getObjectIdsOrBuilderList();
  /**
   * <pre>
   * Batch of storage objects.
   * </pre>
   *
   * <code>repeated .nakama.api.ReadStorageObjectId object_ids = 1 [json_name = "objectIds"];</code>
   */
  com.heroiclabs.nakama.api.ReadStorageObjectIdOrBuilder getObjectIdsOrBuilder(
      int index);
}
