// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/heroiclabs/nakama-common/api/api.proto
// Protobuf Java Version: 4.28.2

package com.heroiclabs.nakama.api;

/**
 * <pre>
 * A list of groups belonging to a user, along with the user's role in each group.
 * </pre>
 *
 * Protobuf type {@code nakama.api.UserGroupList}
 */
public final class UserGroupList extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:nakama.api.UserGroupList)
    UserGroupListOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      UserGroupList.class.getName());
  }
  // Use UserGroupList.newBuilder() to construct.
  private UserGroupList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UserGroupList() {
    userGroups_ = java.util.Collections.emptyList();
    cursor_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.heroiclabs.nakama.api.ApiProto.internal_static_nakama_api_UserGroupList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.heroiclabs.nakama.api.ApiProto.internal_static_nakama_api_UserGroupList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.heroiclabs.nakama.api.UserGroupList.class, com.heroiclabs.nakama.api.UserGroupList.Builder.class);
  }

  public interface UserGroupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:nakama.api.UserGroupList.UserGroup)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Group.
     * </pre>
     *
     * <code>.nakama.api.Group group = 1 [json_name = "group"];</code>
     * @return Whether the group field is set.
     */
    boolean hasGroup();
    /**
     * <pre>
     * Group.
     * </pre>
     *
     * <code>.nakama.api.Group group = 1 [json_name = "group"];</code>
     * @return The group.
     */
    com.heroiclabs.nakama.api.Group getGroup();
    /**
     * <pre>
     * Group.
     * </pre>
     *
     * <code>.nakama.api.Group group = 1 [json_name = "group"];</code>
     */
    com.heroiclabs.nakama.api.GroupOrBuilder getGroupOrBuilder();

    /**
     * <pre>
     * The user's relationship to the group.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value state = 2 [json_name = "state"];</code>
     * @return Whether the state field is set.
     */
    boolean hasState();
    /**
     * <pre>
     * The user's relationship to the group.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value state = 2 [json_name = "state"];</code>
     * @return The state.
     */
    com.google.protobuf.Int32Value getState();
    /**
     * <pre>
     * The user's relationship to the group.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value state = 2 [json_name = "state"];</code>
     */
    com.google.protobuf.Int32ValueOrBuilder getStateOrBuilder();
  }
  /**
   * <pre>
   * A single group-role pair.
   * </pre>
   *
   * Protobuf type {@code nakama.api.UserGroupList.UserGroup}
   */
  public static final class UserGroup extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:nakama.api.UserGroupList.UserGroup)
      UserGroupOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        UserGroup.class.getName());
    }
    // Use UserGroup.newBuilder() to construct.
    private UserGroup(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private UserGroup() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.heroiclabs.nakama.api.ApiProto.internal_static_nakama_api_UserGroupList_UserGroup_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.heroiclabs.nakama.api.ApiProto.internal_static_nakama_api_UserGroupList_UserGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.heroiclabs.nakama.api.UserGroupList.UserGroup.class, com.heroiclabs.nakama.api.UserGroupList.UserGroup.Builder.class);
    }

    /**
     * <pre>
     * The group role status.
     * </pre>
     *
     * Protobuf enum {@code nakama.api.UserGroupList.UserGroup.State}
     */
    public enum State
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * The user is a superadmin with full control of the group.
       * </pre>
       *
       * <code>SUPERADMIN = 0;</code>
       */
      SUPERADMIN(0),
      /**
       * <pre>
       * The user is an admin with additional privileges.
       * </pre>
       *
       * <code>ADMIN = 1;</code>
       */
      ADMIN(1),
      /**
       * <pre>
       * The user is a regular member.
       * </pre>
       *
       * <code>MEMBER = 2;</code>
       */
      MEMBER(2),
      /**
       * <pre>
       * The user has requested to join the group
       * </pre>
       *
       * <code>JOIN_REQUEST = 3;</code>
       */
      JOIN_REQUEST(3),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 28,
          /* patch= */ 2,
          /* suffix= */ "",
          State.class.getName());
      }
      /**
       * <pre>
       * The user is a superadmin with full control of the group.
       * </pre>
       *
       * <code>SUPERADMIN = 0;</code>
       */
      public static final int SUPERADMIN_VALUE = 0;
      /**
       * <pre>
       * The user is an admin with additional privileges.
       * </pre>
       *
       * <code>ADMIN = 1;</code>
       */
      public static final int ADMIN_VALUE = 1;
      /**
       * <pre>
       * The user is a regular member.
       * </pre>
       *
       * <code>MEMBER = 2;</code>
       */
      public static final int MEMBER_VALUE = 2;
      /**
       * <pre>
       * The user has requested to join the group
       * </pre>
       *
       * <code>JOIN_REQUEST = 3;</code>
       */
      public static final int JOIN_REQUEST_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static State valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static State forNumber(int value) {
        switch (value) {
          case 0: return SUPERADMIN;
          case 1: return ADMIN;
          case 2: return MEMBER;
          case 3: return JOIN_REQUEST;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<State>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          State> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<State>() {
              public State findValueByNumber(int number) {
                return State.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.heroiclabs.nakama.api.UserGroupList.UserGroup.getDescriptor().getEnumTypes().get(0);
      }

      private static final State[] VALUES = values();

      public static State valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private State(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:nakama.api.UserGroupList.UserGroup.State)
    }

    private int bitField0_;
    public static final int GROUP_FIELD_NUMBER = 1;
    private com.heroiclabs.nakama.api.Group group_;
    /**
     * <pre>
     * Group.
     * </pre>
     *
     * <code>.nakama.api.Group group = 1 [json_name = "group"];</code>
     * @return Whether the group field is set.
     */
    @java.lang.Override
    public boolean hasGroup() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Group.
     * </pre>
     *
     * <code>.nakama.api.Group group = 1 [json_name = "group"];</code>
     * @return The group.
     */
    @java.lang.Override
    public com.heroiclabs.nakama.api.Group getGroup() {
      return group_ == null ? com.heroiclabs.nakama.api.Group.getDefaultInstance() : group_;
    }
    /**
     * <pre>
     * Group.
     * </pre>
     *
     * <code>.nakama.api.Group group = 1 [json_name = "group"];</code>
     */
    @java.lang.Override
    public com.heroiclabs.nakama.api.GroupOrBuilder getGroupOrBuilder() {
      return group_ == null ? com.heroiclabs.nakama.api.Group.getDefaultInstance() : group_;
    }

    public static final int STATE_FIELD_NUMBER = 2;
    private com.google.protobuf.Int32Value state_;
    /**
     * <pre>
     * The user's relationship to the group.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value state = 2 [json_name = "state"];</code>
     * @return Whether the state field is set.
     */
    @java.lang.Override
    public boolean hasState() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * The user's relationship to the group.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value state = 2 [json_name = "state"];</code>
     * @return The state.
     */
    @java.lang.Override
    public com.google.protobuf.Int32Value getState() {
      return state_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : state_;
    }
    /**
     * <pre>
     * The user's relationship to the group.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value state = 2 [json_name = "state"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.Int32ValueOrBuilder getStateOrBuilder() {
      return state_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : state_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getGroup());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getState());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getGroup());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getState());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.heroiclabs.nakama.api.UserGroupList.UserGroup)) {
        return super.equals(obj);
      }
      com.heroiclabs.nakama.api.UserGroupList.UserGroup other = (com.heroiclabs.nakama.api.UserGroupList.UserGroup) obj;

      if (hasGroup() != other.hasGroup()) return false;
      if (hasGroup()) {
        if (!getGroup()
            .equals(other.getGroup())) return false;
      }
      if (hasState() != other.hasState()) return false;
      if (hasState()) {
        if (!getState()
            .equals(other.getState())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasGroup()) {
        hash = (37 * hash) + GROUP_FIELD_NUMBER;
        hash = (53 * hash) + getGroup().hashCode();
      }
      if (hasState()) {
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + getState().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.heroiclabs.nakama.api.UserGroupList.UserGroup parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.heroiclabs.nakama.api.UserGroupList.UserGroup parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.heroiclabs.nakama.api.UserGroupList.UserGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.heroiclabs.nakama.api.UserGroupList.UserGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.heroiclabs.nakama.api.UserGroupList.UserGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.heroiclabs.nakama.api.UserGroupList.UserGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.heroiclabs.nakama.api.UserGroupList.UserGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.heroiclabs.nakama.api.UserGroupList.UserGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.heroiclabs.nakama.api.UserGroupList.UserGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.heroiclabs.nakama.api.UserGroupList.UserGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.heroiclabs.nakama.api.UserGroupList.UserGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.heroiclabs.nakama.api.UserGroupList.UserGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.heroiclabs.nakama.api.UserGroupList.UserGroup prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A single group-role pair.
     * </pre>
     *
     * Protobuf type {@code nakama.api.UserGroupList.UserGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:nakama.api.UserGroupList.UserGroup)
        com.heroiclabs.nakama.api.UserGroupList.UserGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.heroiclabs.nakama.api.ApiProto.internal_static_nakama_api_UserGroupList_UserGroup_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.heroiclabs.nakama.api.ApiProto.internal_static_nakama_api_UserGroupList_UserGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.heroiclabs.nakama.api.UserGroupList.UserGroup.class, com.heroiclabs.nakama.api.UserGroupList.UserGroup.Builder.class);
      }

      // Construct using com.heroiclabs.nakama.api.UserGroupList.UserGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getGroupFieldBuilder();
          getStateFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        group_ = null;
        if (groupBuilder_ != null) {
          groupBuilder_.dispose();
          groupBuilder_ = null;
        }
        state_ = null;
        if (stateBuilder_ != null) {
          stateBuilder_.dispose();
          stateBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.heroiclabs.nakama.api.ApiProto.internal_static_nakama_api_UserGroupList_UserGroup_descriptor;
      }

      @java.lang.Override
      public com.heroiclabs.nakama.api.UserGroupList.UserGroup getDefaultInstanceForType() {
        return com.heroiclabs.nakama.api.UserGroupList.UserGroup.getDefaultInstance();
      }

      @java.lang.Override
      public com.heroiclabs.nakama.api.UserGroupList.UserGroup build() {
        com.heroiclabs.nakama.api.UserGroupList.UserGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.heroiclabs.nakama.api.UserGroupList.UserGroup buildPartial() {
        com.heroiclabs.nakama.api.UserGroupList.UserGroup result = new com.heroiclabs.nakama.api.UserGroupList.UserGroup(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.heroiclabs.nakama.api.UserGroupList.UserGroup result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.group_ = groupBuilder_ == null
              ? group_
              : groupBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.state_ = stateBuilder_ == null
              ? state_
              : stateBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.heroiclabs.nakama.api.UserGroupList.UserGroup) {
          return mergeFrom((com.heroiclabs.nakama.api.UserGroupList.UserGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.heroiclabs.nakama.api.UserGroupList.UserGroup other) {
        if (other == com.heroiclabs.nakama.api.UserGroupList.UserGroup.getDefaultInstance()) return this;
        if (other.hasGroup()) {
          mergeGroup(other.getGroup());
        }
        if (other.hasState()) {
          mergeState(other.getState());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getGroupFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getStateFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.heroiclabs.nakama.api.Group group_;
      private com.google.protobuf.SingleFieldBuilder<
          com.heroiclabs.nakama.api.Group, com.heroiclabs.nakama.api.Group.Builder, com.heroiclabs.nakama.api.GroupOrBuilder> groupBuilder_;
      /**
       * <pre>
       * Group.
       * </pre>
       *
       * <code>.nakama.api.Group group = 1 [json_name = "group"];</code>
       * @return Whether the group field is set.
       */
      public boolean hasGroup() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Group.
       * </pre>
       *
       * <code>.nakama.api.Group group = 1 [json_name = "group"];</code>
       * @return The group.
       */
      public com.heroiclabs.nakama.api.Group getGroup() {
        if (groupBuilder_ == null) {
          return group_ == null ? com.heroiclabs.nakama.api.Group.getDefaultInstance() : group_;
        } else {
          return groupBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Group.
       * </pre>
       *
       * <code>.nakama.api.Group group = 1 [json_name = "group"];</code>
       */
      public Builder setGroup(com.heroiclabs.nakama.api.Group value) {
        if (groupBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          group_ = value;
        } else {
          groupBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Group.
       * </pre>
       *
       * <code>.nakama.api.Group group = 1 [json_name = "group"];</code>
       */
      public Builder setGroup(
          com.heroiclabs.nakama.api.Group.Builder builderForValue) {
        if (groupBuilder_ == null) {
          group_ = builderForValue.build();
        } else {
          groupBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Group.
       * </pre>
       *
       * <code>.nakama.api.Group group = 1 [json_name = "group"];</code>
       */
      public Builder mergeGroup(com.heroiclabs.nakama.api.Group value) {
        if (groupBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            group_ != null &&
            group_ != com.heroiclabs.nakama.api.Group.getDefaultInstance()) {
            getGroupBuilder().mergeFrom(value);
          } else {
            group_ = value;
          }
        } else {
          groupBuilder_.mergeFrom(value);
        }
        if (group_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * Group.
       * </pre>
       *
       * <code>.nakama.api.Group group = 1 [json_name = "group"];</code>
       */
      public Builder clearGroup() {
        bitField0_ = (bitField0_ & ~0x00000001);
        group_ = null;
        if (groupBuilder_ != null) {
          groupBuilder_.dispose();
          groupBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Group.
       * </pre>
       *
       * <code>.nakama.api.Group group = 1 [json_name = "group"];</code>
       */
      public com.heroiclabs.nakama.api.Group.Builder getGroupBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getGroupFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Group.
       * </pre>
       *
       * <code>.nakama.api.Group group = 1 [json_name = "group"];</code>
       */
      public com.heroiclabs.nakama.api.GroupOrBuilder getGroupOrBuilder() {
        if (groupBuilder_ != null) {
          return groupBuilder_.getMessageOrBuilder();
        } else {
          return group_ == null ?
              com.heroiclabs.nakama.api.Group.getDefaultInstance() : group_;
        }
      }
      /**
       * <pre>
       * Group.
       * </pre>
       *
       * <code>.nakama.api.Group group = 1 [json_name = "group"];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.heroiclabs.nakama.api.Group, com.heroiclabs.nakama.api.Group.Builder, com.heroiclabs.nakama.api.GroupOrBuilder> 
          getGroupFieldBuilder() {
        if (groupBuilder_ == null) {
          groupBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.heroiclabs.nakama.api.Group, com.heroiclabs.nakama.api.Group.Builder, com.heroiclabs.nakama.api.GroupOrBuilder>(
                  getGroup(),
                  getParentForChildren(),
                  isClean());
          group_ = null;
        }
        return groupBuilder_;
      }

      private com.google.protobuf.Int32Value state_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> stateBuilder_;
      /**
       * <pre>
       * The user's relationship to the group.
       * </pre>
       *
       * <code>.google.protobuf.Int32Value state = 2 [json_name = "state"];</code>
       * @return Whether the state field is set.
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * The user's relationship to the group.
       * </pre>
       *
       * <code>.google.protobuf.Int32Value state = 2 [json_name = "state"];</code>
       * @return The state.
       */
      public com.google.protobuf.Int32Value getState() {
        if (stateBuilder_ == null) {
          return state_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : state_;
        } else {
          return stateBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The user's relationship to the group.
       * </pre>
       *
       * <code>.google.protobuf.Int32Value state = 2 [json_name = "state"];</code>
       */
      public Builder setState(com.google.protobuf.Int32Value value) {
        if (stateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          state_ = value;
        } else {
          stateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The user's relationship to the group.
       * </pre>
       *
       * <code>.google.protobuf.Int32Value state = 2 [json_name = "state"];</code>
       */
      public Builder setState(
          com.google.protobuf.Int32Value.Builder builderForValue) {
        if (stateBuilder_ == null) {
          state_ = builderForValue.build();
        } else {
          stateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The user's relationship to the group.
       * </pre>
       *
       * <code>.google.protobuf.Int32Value state = 2 [json_name = "state"];</code>
       */
      public Builder mergeState(com.google.protobuf.Int32Value value) {
        if (stateBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            state_ != null &&
            state_ != com.google.protobuf.Int32Value.getDefaultInstance()) {
            getStateBuilder().mergeFrom(value);
          } else {
            state_ = value;
          }
        } else {
          stateBuilder_.mergeFrom(value);
        }
        if (state_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * The user's relationship to the group.
       * </pre>
       *
       * <code>.google.protobuf.Int32Value state = 2 [json_name = "state"];</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000002);
        state_ = null;
        if (stateBuilder_ != null) {
          stateBuilder_.dispose();
          stateBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The user's relationship to the group.
       * </pre>
       *
       * <code>.google.protobuf.Int32Value state = 2 [json_name = "state"];</code>
       */
      public com.google.protobuf.Int32Value.Builder getStateBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getStateFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The user's relationship to the group.
       * </pre>
       *
       * <code>.google.protobuf.Int32Value state = 2 [json_name = "state"];</code>
       */
      public com.google.protobuf.Int32ValueOrBuilder getStateOrBuilder() {
        if (stateBuilder_ != null) {
          return stateBuilder_.getMessageOrBuilder();
        } else {
          return state_ == null ?
              com.google.protobuf.Int32Value.getDefaultInstance() : state_;
        }
      }
      /**
       * <pre>
       * The user's relationship to the group.
       * </pre>
       *
       * <code>.google.protobuf.Int32Value state = 2 [json_name = "state"];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
          getStateFieldBuilder() {
        if (stateBuilder_ == null) {
          stateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                  getState(),
                  getParentForChildren(),
                  isClean());
          state_ = null;
        }
        return stateBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:nakama.api.UserGroupList.UserGroup)
    }

    // @@protoc_insertion_point(class_scope:nakama.api.UserGroupList.UserGroup)
    private static final com.heroiclabs.nakama.api.UserGroupList.UserGroup DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.heroiclabs.nakama.api.UserGroupList.UserGroup();
    }

    public static com.heroiclabs.nakama.api.UserGroupList.UserGroup getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserGroup>
        PARSER = new com.google.protobuf.AbstractParser<UserGroup>() {
      @java.lang.Override
      public UserGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UserGroup> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserGroup> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.heroiclabs.nakama.api.UserGroupList.UserGroup getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int USER_GROUPS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.heroiclabs.nakama.api.UserGroupList.UserGroup> userGroups_;
  /**
   * <pre>
   * Group-role pairs for a user.
   * </pre>
   *
   * <code>repeated .nakama.api.UserGroupList.UserGroup user_groups = 1 [json_name = "userGroups"];</code>
   */
  @java.lang.Override
  public java.util.List<com.heroiclabs.nakama.api.UserGroupList.UserGroup> getUserGroupsList() {
    return userGroups_;
  }
  /**
   * <pre>
   * Group-role pairs for a user.
   * </pre>
   *
   * <code>repeated .nakama.api.UserGroupList.UserGroup user_groups = 1 [json_name = "userGroups"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.heroiclabs.nakama.api.UserGroupList.UserGroupOrBuilder> 
      getUserGroupsOrBuilderList() {
    return userGroups_;
  }
  /**
   * <pre>
   * Group-role pairs for a user.
   * </pre>
   *
   * <code>repeated .nakama.api.UserGroupList.UserGroup user_groups = 1 [json_name = "userGroups"];</code>
   */
  @java.lang.Override
  public int getUserGroupsCount() {
    return userGroups_.size();
  }
  /**
   * <pre>
   * Group-role pairs for a user.
   * </pre>
   *
   * <code>repeated .nakama.api.UserGroupList.UserGroup user_groups = 1 [json_name = "userGroups"];</code>
   */
  @java.lang.Override
  public com.heroiclabs.nakama.api.UserGroupList.UserGroup getUserGroups(int index) {
    return userGroups_.get(index);
  }
  /**
   * <pre>
   * Group-role pairs for a user.
   * </pre>
   *
   * <code>repeated .nakama.api.UserGroupList.UserGroup user_groups = 1 [json_name = "userGroups"];</code>
   */
  @java.lang.Override
  public com.heroiclabs.nakama.api.UserGroupList.UserGroupOrBuilder getUserGroupsOrBuilder(
      int index) {
    return userGroups_.get(index);
  }

  public static final int CURSOR_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object cursor_ = "";
  /**
   * <pre>
   * Cursor for the next page of results, if any.
   * </pre>
   *
   * <code>string cursor = 2 [json_name = "cursor"];</code>
   * @return The cursor.
   */
  @java.lang.Override
  public java.lang.String getCursor() {
    java.lang.Object ref = cursor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cursor_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Cursor for the next page of results, if any.
   * </pre>
   *
   * <code>string cursor = 2 [json_name = "cursor"];</code>
   * @return The bytes for cursor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCursorBytes() {
    java.lang.Object ref = cursor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cursor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < userGroups_.size(); i++) {
      output.writeMessage(1, userGroups_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(cursor_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, cursor_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < userGroups_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, userGroups_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(cursor_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, cursor_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.heroiclabs.nakama.api.UserGroupList)) {
      return super.equals(obj);
    }
    com.heroiclabs.nakama.api.UserGroupList other = (com.heroiclabs.nakama.api.UserGroupList) obj;

    if (!getUserGroupsList()
        .equals(other.getUserGroupsList())) return false;
    if (!getCursor()
        .equals(other.getCursor())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUserGroupsCount() > 0) {
      hash = (37 * hash) + USER_GROUPS_FIELD_NUMBER;
      hash = (53 * hash) + getUserGroupsList().hashCode();
    }
    hash = (37 * hash) + CURSOR_FIELD_NUMBER;
    hash = (53 * hash) + getCursor().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.heroiclabs.nakama.api.UserGroupList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.heroiclabs.nakama.api.UserGroupList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.heroiclabs.nakama.api.UserGroupList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.heroiclabs.nakama.api.UserGroupList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.heroiclabs.nakama.api.UserGroupList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.heroiclabs.nakama.api.UserGroupList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.heroiclabs.nakama.api.UserGroupList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.heroiclabs.nakama.api.UserGroupList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.heroiclabs.nakama.api.UserGroupList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.heroiclabs.nakama.api.UserGroupList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.heroiclabs.nakama.api.UserGroupList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.heroiclabs.nakama.api.UserGroupList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.heroiclabs.nakama.api.UserGroupList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A list of groups belonging to a user, along with the user's role in each group.
   * </pre>
   *
   * Protobuf type {@code nakama.api.UserGroupList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nakama.api.UserGroupList)
      com.heroiclabs.nakama.api.UserGroupListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.heroiclabs.nakama.api.ApiProto.internal_static_nakama_api_UserGroupList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.heroiclabs.nakama.api.ApiProto.internal_static_nakama_api_UserGroupList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.heroiclabs.nakama.api.UserGroupList.class, com.heroiclabs.nakama.api.UserGroupList.Builder.class);
    }

    // Construct using com.heroiclabs.nakama.api.UserGroupList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (userGroupsBuilder_ == null) {
        userGroups_ = java.util.Collections.emptyList();
      } else {
        userGroups_ = null;
        userGroupsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      cursor_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.heroiclabs.nakama.api.ApiProto.internal_static_nakama_api_UserGroupList_descriptor;
    }

    @java.lang.Override
    public com.heroiclabs.nakama.api.UserGroupList getDefaultInstanceForType() {
      return com.heroiclabs.nakama.api.UserGroupList.getDefaultInstance();
    }

    @java.lang.Override
    public com.heroiclabs.nakama.api.UserGroupList build() {
      com.heroiclabs.nakama.api.UserGroupList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.heroiclabs.nakama.api.UserGroupList buildPartial() {
      com.heroiclabs.nakama.api.UserGroupList result = new com.heroiclabs.nakama.api.UserGroupList(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.heroiclabs.nakama.api.UserGroupList result) {
      if (userGroupsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          userGroups_ = java.util.Collections.unmodifiableList(userGroups_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.userGroups_ = userGroups_;
      } else {
        result.userGroups_ = userGroupsBuilder_.build();
      }
    }

    private void buildPartial0(com.heroiclabs.nakama.api.UserGroupList result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.cursor_ = cursor_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.heroiclabs.nakama.api.UserGroupList) {
        return mergeFrom((com.heroiclabs.nakama.api.UserGroupList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.heroiclabs.nakama.api.UserGroupList other) {
      if (other == com.heroiclabs.nakama.api.UserGroupList.getDefaultInstance()) return this;
      if (userGroupsBuilder_ == null) {
        if (!other.userGroups_.isEmpty()) {
          if (userGroups_.isEmpty()) {
            userGroups_ = other.userGroups_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUserGroupsIsMutable();
            userGroups_.addAll(other.userGroups_);
          }
          onChanged();
        }
      } else {
        if (!other.userGroups_.isEmpty()) {
          if (userGroupsBuilder_.isEmpty()) {
            userGroupsBuilder_.dispose();
            userGroupsBuilder_ = null;
            userGroups_ = other.userGroups_;
            bitField0_ = (bitField0_ & ~0x00000001);
            userGroupsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getUserGroupsFieldBuilder() : null;
          } else {
            userGroupsBuilder_.addAllMessages(other.userGroups_);
          }
        }
      }
      if (!other.getCursor().isEmpty()) {
        cursor_ = other.cursor_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.heroiclabs.nakama.api.UserGroupList.UserGroup m =
                  input.readMessage(
                      com.heroiclabs.nakama.api.UserGroupList.UserGroup.parser(),
                      extensionRegistry);
              if (userGroupsBuilder_ == null) {
                ensureUserGroupsIsMutable();
                userGroups_.add(m);
              } else {
                userGroupsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              cursor_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.heroiclabs.nakama.api.UserGroupList.UserGroup> userGroups_ =
      java.util.Collections.emptyList();
    private void ensureUserGroupsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        userGroups_ = new java.util.ArrayList<com.heroiclabs.nakama.api.UserGroupList.UserGroup>(userGroups_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.heroiclabs.nakama.api.UserGroupList.UserGroup, com.heroiclabs.nakama.api.UserGroupList.UserGroup.Builder, com.heroiclabs.nakama.api.UserGroupList.UserGroupOrBuilder> userGroupsBuilder_;

    /**
     * <pre>
     * Group-role pairs for a user.
     * </pre>
     *
     * <code>repeated .nakama.api.UserGroupList.UserGroup user_groups = 1 [json_name = "userGroups"];</code>
     */
    public java.util.List<com.heroiclabs.nakama.api.UserGroupList.UserGroup> getUserGroupsList() {
      if (userGroupsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(userGroups_);
      } else {
        return userGroupsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Group-role pairs for a user.
     * </pre>
     *
     * <code>repeated .nakama.api.UserGroupList.UserGroup user_groups = 1 [json_name = "userGroups"];</code>
     */
    public int getUserGroupsCount() {
      if (userGroupsBuilder_ == null) {
        return userGroups_.size();
      } else {
        return userGroupsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Group-role pairs for a user.
     * </pre>
     *
     * <code>repeated .nakama.api.UserGroupList.UserGroup user_groups = 1 [json_name = "userGroups"];</code>
     */
    public com.heroiclabs.nakama.api.UserGroupList.UserGroup getUserGroups(int index) {
      if (userGroupsBuilder_ == null) {
        return userGroups_.get(index);
      } else {
        return userGroupsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Group-role pairs for a user.
     * </pre>
     *
     * <code>repeated .nakama.api.UserGroupList.UserGroup user_groups = 1 [json_name = "userGroups"];</code>
     */
    public Builder setUserGroups(
        int index, com.heroiclabs.nakama.api.UserGroupList.UserGroup value) {
      if (userGroupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserGroupsIsMutable();
        userGroups_.set(index, value);
        onChanged();
      } else {
        userGroupsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Group-role pairs for a user.
     * </pre>
     *
     * <code>repeated .nakama.api.UserGroupList.UserGroup user_groups = 1 [json_name = "userGroups"];</code>
     */
    public Builder setUserGroups(
        int index, com.heroiclabs.nakama.api.UserGroupList.UserGroup.Builder builderForValue) {
      if (userGroupsBuilder_ == null) {
        ensureUserGroupsIsMutable();
        userGroups_.set(index, builderForValue.build());
        onChanged();
      } else {
        userGroupsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Group-role pairs for a user.
     * </pre>
     *
     * <code>repeated .nakama.api.UserGroupList.UserGroup user_groups = 1 [json_name = "userGroups"];</code>
     */
    public Builder addUserGroups(com.heroiclabs.nakama.api.UserGroupList.UserGroup value) {
      if (userGroupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserGroupsIsMutable();
        userGroups_.add(value);
        onChanged();
      } else {
        userGroupsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Group-role pairs for a user.
     * </pre>
     *
     * <code>repeated .nakama.api.UserGroupList.UserGroup user_groups = 1 [json_name = "userGroups"];</code>
     */
    public Builder addUserGroups(
        int index, com.heroiclabs.nakama.api.UserGroupList.UserGroup value) {
      if (userGroupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserGroupsIsMutable();
        userGroups_.add(index, value);
        onChanged();
      } else {
        userGroupsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Group-role pairs for a user.
     * </pre>
     *
     * <code>repeated .nakama.api.UserGroupList.UserGroup user_groups = 1 [json_name = "userGroups"];</code>
     */
    public Builder addUserGroups(
        com.heroiclabs.nakama.api.UserGroupList.UserGroup.Builder builderForValue) {
      if (userGroupsBuilder_ == null) {
        ensureUserGroupsIsMutable();
        userGroups_.add(builderForValue.build());
        onChanged();
      } else {
        userGroupsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Group-role pairs for a user.
     * </pre>
     *
     * <code>repeated .nakama.api.UserGroupList.UserGroup user_groups = 1 [json_name = "userGroups"];</code>
     */
    public Builder addUserGroups(
        int index, com.heroiclabs.nakama.api.UserGroupList.UserGroup.Builder builderForValue) {
      if (userGroupsBuilder_ == null) {
        ensureUserGroupsIsMutable();
        userGroups_.add(index, builderForValue.build());
        onChanged();
      } else {
        userGroupsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Group-role pairs for a user.
     * </pre>
     *
     * <code>repeated .nakama.api.UserGroupList.UserGroup user_groups = 1 [json_name = "userGroups"];</code>
     */
    public Builder addAllUserGroups(
        java.lang.Iterable<? extends com.heroiclabs.nakama.api.UserGroupList.UserGroup> values) {
      if (userGroupsBuilder_ == null) {
        ensureUserGroupsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, userGroups_);
        onChanged();
      } else {
        userGroupsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Group-role pairs for a user.
     * </pre>
     *
     * <code>repeated .nakama.api.UserGroupList.UserGroup user_groups = 1 [json_name = "userGroups"];</code>
     */
    public Builder clearUserGroups() {
      if (userGroupsBuilder_ == null) {
        userGroups_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        userGroupsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Group-role pairs for a user.
     * </pre>
     *
     * <code>repeated .nakama.api.UserGroupList.UserGroup user_groups = 1 [json_name = "userGroups"];</code>
     */
    public Builder removeUserGroups(int index) {
      if (userGroupsBuilder_ == null) {
        ensureUserGroupsIsMutable();
        userGroups_.remove(index);
        onChanged();
      } else {
        userGroupsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Group-role pairs for a user.
     * </pre>
     *
     * <code>repeated .nakama.api.UserGroupList.UserGroup user_groups = 1 [json_name = "userGroups"];</code>
     */
    public com.heroiclabs.nakama.api.UserGroupList.UserGroup.Builder getUserGroupsBuilder(
        int index) {
      return getUserGroupsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Group-role pairs for a user.
     * </pre>
     *
     * <code>repeated .nakama.api.UserGroupList.UserGroup user_groups = 1 [json_name = "userGroups"];</code>
     */
    public com.heroiclabs.nakama.api.UserGroupList.UserGroupOrBuilder getUserGroupsOrBuilder(
        int index) {
      if (userGroupsBuilder_ == null) {
        return userGroups_.get(index);  } else {
        return userGroupsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Group-role pairs for a user.
     * </pre>
     *
     * <code>repeated .nakama.api.UserGroupList.UserGroup user_groups = 1 [json_name = "userGroups"];</code>
     */
    public java.util.List<? extends com.heroiclabs.nakama.api.UserGroupList.UserGroupOrBuilder> 
         getUserGroupsOrBuilderList() {
      if (userGroupsBuilder_ != null) {
        return userGroupsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(userGroups_);
      }
    }
    /**
     * <pre>
     * Group-role pairs for a user.
     * </pre>
     *
     * <code>repeated .nakama.api.UserGroupList.UserGroup user_groups = 1 [json_name = "userGroups"];</code>
     */
    public com.heroiclabs.nakama.api.UserGroupList.UserGroup.Builder addUserGroupsBuilder() {
      return getUserGroupsFieldBuilder().addBuilder(
          com.heroiclabs.nakama.api.UserGroupList.UserGroup.getDefaultInstance());
    }
    /**
     * <pre>
     * Group-role pairs for a user.
     * </pre>
     *
     * <code>repeated .nakama.api.UserGroupList.UserGroup user_groups = 1 [json_name = "userGroups"];</code>
     */
    public com.heroiclabs.nakama.api.UserGroupList.UserGroup.Builder addUserGroupsBuilder(
        int index) {
      return getUserGroupsFieldBuilder().addBuilder(
          index, com.heroiclabs.nakama.api.UserGroupList.UserGroup.getDefaultInstance());
    }
    /**
     * <pre>
     * Group-role pairs for a user.
     * </pre>
     *
     * <code>repeated .nakama.api.UserGroupList.UserGroup user_groups = 1 [json_name = "userGroups"];</code>
     */
    public java.util.List<com.heroiclabs.nakama.api.UserGroupList.UserGroup.Builder> 
         getUserGroupsBuilderList() {
      return getUserGroupsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.heroiclabs.nakama.api.UserGroupList.UserGroup, com.heroiclabs.nakama.api.UserGroupList.UserGroup.Builder, com.heroiclabs.nakama.api.UserGroupList.UserGroupOrBuilder> 
        getUserGroupsFieldBuilder() {
      if (userGroupsBuilder_ == null) {
        userGroupsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.heroiclabs.nakama.api.UserGroupList.UserGroup, com.heroiclabs.nakama.api.UserGroupList.UserGroup.Builder, com.heroiclabs.nakama.api.UserGroupList.UserGroupOrBuilder>(
                userGroups_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        userGroups_ = null;
      }
      return userGroupsBuilder_;
    }

    private java.lang.Object cursor_ = "";
    /**
     * <pre>
     * Cursor for the next page of results, if any.
     * </pre>
     *
     * <code>string cursor = 2 [json_name = "cursor"];</code>
     * @return The cursor.
     */
    public java.lang.String getCursor() {
      java.lang.Object ref = cursor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cursor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Cursor for the next page of results, if any.
     * </pre>
     *
     * <code>string cursor = 2 [json_name = "cursor"];</code>
     * @return The bytes for cursor.
     */
    public com.google.protobuf.ByteString
        getCursorBytes() {
      java.lang.Object ref = cursor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cursor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Cursor for the next page of results, if any.
     * </pre>
     *
     * <code>string cursor = 2 [json_name = "cursor"];</code>
     * @param value The cursor to set.
     * @return This builder for chaining.
     */
    public Builder setCursor(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      cursor_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Cursor for the next page of results, if any.
     * </pre>
     *
     * <code>string cursor = 2 [json_name = "cursor"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCursor() {
      cursor_ = getDefaultInstance().getCursor();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Cursor for the next page of results, if any.
     * </pre>
     *
     * <code>string cursor = 2 [json_name = "cursor"];</code>
     * @param value The bytes for cursor to set.
     * @return This builder for chaining.
     */
    public Builder setCursorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      cursor_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:nakama.api.UserGroupList)
  }

  // @@protoc_insertion_point(class_scope:nakama.api.UserGroupList)
  private static final com.heroiclabs.nakama.api.UserGroupList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.heroiclabs.nakama.api.UserGroupList();
  }

  public static com.heroiclabs.nakama.api.UserGroupList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserGroupList>
      PARSER = new com.google.protobuf.AbstractParser<UserGroupList>() {
    @java.lang.Override
    public UserGroupList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UserGroupList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserGroupList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.heroiclabs.nakama.api.UserGroupList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

