// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/heroiclabs/nakama-common/rtapi/realtime.proto
// Protobuf Java Version: 4.28.2

package com.heroiclabs.nakama.rtapi;

/**
 * <pre>
 * A receipt reply from a channel message send operation.
 * </pre>
 *
 * Protobuf type {@code nakama.realtime.ChannelMessageAck}
 */
public final class ChannelMessageAck extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:nakama.realtime.ChannelMessageAck)
    ChannelMessageAckOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      ChannelMessageAck.class.getName());
  }
  // Use ChannelMessageAck.newBuilder() to construct.
  private ChannelMessageAck(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ChannelMessageAck() {
    channelId_ = "";
    messageId_ = "";
    username_ = "";
    roomName_ = "";
    groupId_ = "";
    userIdOne_ = "";
    userIdTwo_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.heroiclabs.nakama.rtapi.RealtimeProto.internal_static_nakama_realtime_ChannelMessageAck_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.heroiclabs.nakama.rtapi.RealtimeProto.internal_static_nakama_realtime_ChannelMessageAck_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.heroiclabs.nakama.rtapi.ChannelMessageAck.class, com.heroiclabs.nakama.rtapi.ChannelMessageAck.Builder.class);
  }

  private int bitField0_;
  public static final int CHANNEL_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object channelId_ = "";
  /**
   * <pre>
   * The channel the message was sent to.
   * </pre>
   *
   * <code>string channel_id = 1 [json_name = "channelId"];</code>
   * @return The channelId.
   */
  @java.lang.Override
  public java.lang.String getChannelId() {
    java.lang.Object ref = channelId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      channelId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The channel the message was sent to.
   * </pre>
   *
   * <code>string channel_id = 1 [json_name = "channelId"];</code>
   * @return The bytes for channelId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChannelIdBytes() {
    java.lang.Object ref = channelId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      channelId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object messageId_ = "";
  /**
   * <pre>
   * The unique ID assigned to the message.
   * </pre>
   *
   * <code>string message_id = 2 [json_name = "messageId"];</code>
   * @return The messageId.
   */
  @java.lang.Override
  public java.lang.String getMessageId() {
    java.lang.Object ref = messageId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      messageId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The unique ID assigned to the message.
   * </pre>
   *
   * <code>string message_id = 2 [json_name = "messageId"];</code>
   * @return The bytes for messageId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageIdBytes() {
    java.lang.Object ref = messageId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      messageId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CODE_FIELD_NUMBER = 3;
  private com.google.protobuf.Int32Value code_;
  /**
   * <pre>
   * The code representing a message type or category.
   * </pre>
   *
   * <code>.google.protobuf.Int32Value code = 3 [json_name = "code"];</code>
   * @return Whether the code field is set.
   */
  @java.lang.Override
  public boolean hasCode() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The code representing a message type or category.
   * </pre>
   *
   * <code>.google.protobuf.Int32Value code = 3 [json_name = "code"];</code>
   * @return The code.
   */
  @java.lang.Override
  public com.google.protobuf.Int32Value getCode() {
    return code_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : code_;
  }
  /**
   * <pre>
   * The code representing a message type or category.
   * </pre>
   *
   * <code>.google.protobuf.Int32Value code = 3 [json_name = "code"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.Int32ValueOrBuilder getCodeOrBuilder() {
    return code_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : code_;
  }

  public static final int USERNAME_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object username_ = "";
  /**
   * <pre>
   * Username of the message sender.
   * </pre>
   *
   * <code>string username = 4 [json_name = "username"];</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Username of the message sender.
   * </pre>
   *
   * <code>string username = 4 [json_name = "username"];</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATE_TIME_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp createTime_;
  /**
   * <pre>
   * The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp create_time = 5 [json_name = "createTime"];</code>
   * @return Whether the createTime field is set.
   */
  @java.lang.Override
  public boolean hasCreateTime() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp create_time = 5 [json_name = "createTime"];</code>
   * @return The createTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreateTime() {
    return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
  }
  /**
   * <pre>
   * The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp create_time = 5 [json_name = "createTime"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder() {
    return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
  }

  public static final int UPDATE_TIME_FIELD_NUMBER = 6;
  private com.google.protobuf.Timestamp updateTime_;
  /**
   * <pre>
   * The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was last updated.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp update_time = 6 [json_name = "updateTime"];</code>
   * @return Whether the updateTime field is set.
   */
  @java.lang.Override
  public boolean hasUpdateTime() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was last updated.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp update_time = 6 [json_name = "updateTime"];</code>
   * @return The updateTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getUpdateTime() {
    return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
  }
  /**
   * <pre>
   * The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was last updated.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp update_time = 6 [json_name = "updateTime"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder() {
    return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
  }

  public static final int PERSISTENT_FIELD_NUMBER = 7;
  private com.google.protobuf.BoolValue persistent_;
  /**
   * <pre>
   * True if the message was persisted to the channel's history, false otherwise.
   * </pre>
   *
   * <code>.google.protobuf.BoolValue persistent = 7 [json_name = "persistent"];</code>
   * @return Whether the persistent field is set.
   */
  @java.lang.Override
  public boolean hasPersistent() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * True if the message was persisted to the channel's history, false otherwise.
   * </pre>
   *
   * <code>.google.protobuf.BoolValue persistent = 7 [json_name = "persistent"];</code>
   * @return The persistent.
   */
  @java.lang.Override
  public com.google.protobuf.BoolValue getPersistent() {
    return persistent_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : persistent_;
  }
  /**
   * <pre>
   * True if the message was persisted to the channel's history, false otherwise.
   * </pre>
   *
   * <code>.google.protobuf.BoolValue persistent = 7 [json_name = "persistent"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.BoolValueOrBuilder getPersistentOrBuilder() {
    return persistent_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : persistent_;
  }

  public static final int ROOM_NAME_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object roomName_ = "";
  /**
   * <pre>
   * The name of the chat room, or an empty string if this message was not sent through a chat room.
   * </pre>
   *
   * <code>string room_name = 8 [json_name = "roomName"];</code>
   * @return The roomName.
   */
  @java.lang.Override
  public java.lang.String getRoomName() {
    java.lang.Object ref = roomName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      roomName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The name of the chat room, or an empty string if this message was not sent through a chat room.
   * </pre>
   *
   * <code>string room_name = 8 [json_name = "roomName"];</code>
   * @return The bytes for roomName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRoomNameBytes() {
    java.lang.Object ref = roomName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roomName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GROUP_ID_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object groupId_ = "";
  /**
   * <pre>
   * The ID of the group, or an empty string if this message was not sent through a group channel.
   * </pre>
   *
   * <code>string group_id = 9 [json_name = "groupId"];</code>
   * @return The groupId.
   */
  @java.lang.Override
  public java.lang.String getGroupId() {
    java.lang.Object ref = groupId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      groupId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The ID of the group, or an empty string if this message was not sent through a group channel.
   * </pre>
   *
   * <code>string group_id = 9 [json_name = "groupId"];</code>
   * @return The bytes for groupId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGroupIdBytes() {
    java.lang.Object ref = groupId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      groupId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_ID_ONE_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userIdOne_ = "";
  /**
   * <pre>
   * The ID of the first DM user, or an empty string if this message was not sent through a DM chat.
   * </pre>
   *
   * <code>string user_id_one = 10 [json_name = "userIdOne"];</code>
   * @return The userIdOne.
   */
  @java.lang.Override
  public java.lang.String getUserIdOne() {
    java.lang.Object ref = userIdOne_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userIdOne_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The ID of the first DM user, or an empty string if this message was not sent through a DM chat.
   * </pre>
   *
   * <code>string user_id_one = 10 [json_name = "userIdOne"];</code>
   * @return The bytes for userIdOne.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdOneBytes() {
    java.lang.Object ref = userIdOne_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userIdOne_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_ID_TWO_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userIdTwo_ = "";
  /**
   * <pre>
   * The ID of the second DM user, or an empty string if this message was not sent through a DM chat.
   * </pre>
   *
   * <code>string user_id_two = 11 [json_name = "userIdTwo"];</code>
   * @return The userIdTwo.
   */
  @java.lang.Override
  public java.lang.String getUserIdTwo() {
    java.lang.Object ref = userIdTwo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userIdTwo_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The ID of the second DM user, or an empty string if this message was not sent through a DM chat.
   * </pre>
   *
   * <code>string user_id_two = 11 [json_name = "userIdTwo"];</code>
   * @return The bytes for userIdTwo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdTwoBytes() {
    java.lang.Object ref = userIdTwo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userIdTwo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(channelId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, channelId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(messageId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, messageId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getCode());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(username_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, username_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(5, getCreateTime());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(6, getUpdateTime());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(7, getPersistent());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(roomName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, roomName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(groupId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, groupId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userIdOne_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, userIdOne_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userIdTwo_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 11, userIdTwo_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(channelId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, channelId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(messageId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, messageId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getCode());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(username_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, username_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getCreateTime());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getUpdateTime());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getPersistent());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(roomName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, roomName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(groupId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, groupId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userIdOne_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, userIdOne_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userIdTwo_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(11, userIdTwo_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.heroiclabs.nakama.rtapi.ChannelMessageAck)) {
      return super.equals(obj);
    }
    com.heroiclabs.nakama.rtapi.ChannelMessageAck other = (com.heroiclabs.nakama.rtapi.ChannelMessageAck) obj;

    if (!getChannelId()
        .equals(other.getChannelId())) return false;
    if (!getMessageId()
        .equals(other.getMessageId())) return false;
    if (hasCode() != other.hasCode()) return false;
    if (hasCode()) {
      if (!getCode()
          .equals(other.getCode())) return false;
    }
    if (!getUsername()
        .equals(other.getUsername())) return false;
    if (hasCreateTime() != other.hasCreateTime()) return false;
    if (hasCreateTime()) {
      if (!getCreateTime()
          .equals(other.getCreateTime())) return false;
    }
    if (hasUpdateTime() != other.hasUpdateTime()) return false;
    if (hasUpdateTime()) {
      if (!getUpdateTime()
          .equals(other.getUpdateTime())) return false;
    }
    if (hasPersistent() != other.hasPersistent()) return false;
    if (hasPersistent()) {
      if (!getPersistent()
          .equals(other.getPersistent())) return false;
    }
    if (!getRoomName()
        .equals(other.getRoomName())) return false;
    if (!getGroupId()
        .equals(other.getGroupId())) return false;
    if (!getUserIdOne()
        .equals(other.getUserIdOne())) return false;
    if (!getUserIdTwo()
        .equals(other.getUserIdTwo())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CHANNEL_ID_FIELD_NUMBER;
    hash = (53 * hash) + getChannelId().hashCode();
    hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getMessageId().hashCode();
    if (hasCode()) {
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode().hashCode();
    }
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    if (hasCreateTime()) {
      hash = (37 * hash) + CREATE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getCreateTime().hashCode();
    }
    if (hasUpdateTime()) {
      hash = (37 * hash) + UPDATE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateTime().hashCode();
    }
    if (hasPersistent()) {
      hash = (37 * hash) + PERSISTENT_FIELD_NUMBER;
      hash = (53 * hash) + getPersistent().hashCode();
    }
    hash = (37 * hash) + ROOM_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getRoomName().hashCode();
    hash = (37 * hash) + GROUP_ID_FIELD_NUMBER;
    hash = (53 * hash) + getGroupId().hashCode();
    hash = (37 * hash) + USER_ID_ONE_FIELD_NUMBER;
    hash = (53 * hash) + getUserIdOne().hashCode();
    hash = (37 * hash) + USER_ID_TWO_FIELD_NUMBER;
    hash = (53 * hash) + getUserIdTwo().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.heroiclabs.nakama.rtapi.ChannelMessageAck parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.heroiclabs.nakama.rtapi.ChannelMessageAck parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.heroiclabs.nakama.rtapi.ChannelMessageAck parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.heroiclabs.nakama.rtapi.ChannelMessageAck parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.heroiclabs.nakama.rtapi.ChannelMessageAck parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.heroiclabs.nakama.rtapi.ChannelMessageAck parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.heroiclabs.nakama.rtapi.ChannelMessageAck parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.heroiclabs.nakama.rtapi.ChannelMessageAck parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.heroiclabs.nakama.rtapi.ChannelMessageAck parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.heroiclabs.nakama.rtapi.ChannelMessageAck parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.heroiclabs.nakama.rtapi.ChannelMessageAck parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.heroiclabs.nakama.rtapi.ChannelMessageAck parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.heroiclabs.nakama.rtapi.ChannelMessageAck prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A receipt reply from a channel message send operation.
   * </pre>
   *
   * Protobuf type {@code nakama.realtime.ChannelMessageAck}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nakama.realtime.ChannelMessageAck)
      com.heroiclabs.nakama.rtapi.ChannelMessageAckOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.heroiclabs.nakama.rtapi.RealtimeProto.internal_static_nakama_realtime_ChannelMessageAck_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.heroiclabs.nakama.rtapi.RealtimeProto.internal_static_nakama_realtime_ChannelMessageAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.heroiclabs.nakama.rtapi.ChannelMessageAck.class, com.heroiclabs.nakama.rtapi.ChannelMessageAck.Builder.class);
    }

    // Construct using com.heroiclabs.nakama.rtapi.ChannelMessageAck.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getCodeFieldBuilder();
        getCreateTimeFieldBuilder();
        getUpdateTimeFieldBuilder();
        getPersistentFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      channelId_ = "";
      messageId_ = "";
      code_ = null;
      if (codeBuilder_ != null) {
        codeBuilder_.dispose();
        codeBuilder_ = null;
      }
      username_ = "";
      createTime_ = null;
      if (createTimeBuilder_ != null) {
        createTimeBuilder_.dispose();
        createTimeBuilder_ = null;
      }
      updateTime_ = null;
      if (updateTimeBuilder_ != null) {
        updateTimeBuilder_.dispose();
        updateTimeBuilder_ = null;
      }
      persistent_ = null;
      if (persistentBuilder_ != null) {
        persistentBuilder_.dispose();
        persistentBuilder_ = null;
      }
      roomName_ = "";
      groupId_ = "";
      userIdOne_ = "";
      userIdTwo_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.heroiclabs.nakama.rtapi.RealtimeProto.internal_static_nakama_realtime_ChannelMessageAck_descriptor;
    }

    @java.lang.Override
    public com.heroiclabs.nakama.rtapi.ChannelMessageAck getDefaultInstanceForType() {
      return com.heroiclabs.nakama.rtapi.ChannelMessageAck.getDefaultInstance();
    }

    @java.lang.Override
    public com.heroiclabs.nakama.rtapi.ChannelMessageAck build() {
      com.heroiclabs.nakama.rtapi.ChannelMessageAck result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.heroiclabs.nakama.rtapi.ChannelMessageAck buildPartial() {
      com.heroiclabs.nakama.rtapi.ChannelMessageAck result = new com.heroiclabs.nakama.rtapi.ChannelMessageAck(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.heroiclabs.nakama.rtapi.ChannelMessageAck result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.channelId_ = channelId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.messageId_ = messageId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.code_ = codeBuilder_ == null
            ? code_
            : codeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.username_ = username_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.createTime_ = createTimeBuilder_ == null
            ? createTime_
            : createTimeBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.updateTime_ = updateTimeBuilder_ == null
            ? updateTime_
            : updateTimeBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.persistent_ = persistentBuilder_ == null
            ? persistent_
            : persistentBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.roomName_ = roomName_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.groupId_ = groupId_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.userIdOne_ = userIdOne_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.userIdTwo_ = userIdTwo_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.heroiclabs.nakama.rtapi.ChannelMessageAck) {
        return mergeFrom((com.heroiclabs.nakama.rtapi.ChannelMessageAck)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.heroiclabs.nakama.rtapi.ChannelMessageAck other) {
      if (other == com.heroiclabs.nakama.rtapi.ChannelMessageAck.getDefaultInstance()) return this;
      if (!other.getChannelId().isEmpty()) {
        channelId_ = other.channelId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getMessageId().isEmpty()) {
        messageId_ = other.messageId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasCode()) {
        mergeCode(other.getCode());
      }
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasCreateTime()) {
        mergeCreateTime(other.getCreateTime());
      }
      if (other.hasUpdateTime()) {
        mergeUpdateTime(other.getUpdateTime());
      }
      if (other.hasPersistent()) {
        mergePersistent(other.getPersistent());
      }
      if (!other.getRoomName().isEmpty()) {
        roomName_ = other.roomName_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getGroupId().isEmpty()) {
        groupId_ = other.groupId_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getUserIdOne().isEmpty()) {
        userIdOne_ = other.userIdOne_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (!other.getUserIdTwo().isEmpty()) {
        userIdTwo_ = other.userIdTwo_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              channelId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              messageId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getCodeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              username_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getCreateTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getUpdateTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getPersistentFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              roomName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              groupId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              userIdOne_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              userIdTwo_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object channelId_ = "";
    /**
     * <pre>
     * The channel the message was sent to.
     * </pre>
     *
     * <code>string channel_id = 1 [json_name = "channelId"];</code>
     * @return The channelId.
     */
    public java.lang.String getChannelId() {
      java.lang.Object ref = channelId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        channelId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The channel the message was sent to.
     * </pre>
     *
     * <code>string channel_id = 1 [json_name = "channelId"];</code>
     * @return The bytes for channelId.
     */
    public com.google.protobuf.ByteString
        getChannelIdBytes() {
      java.lang.Object ref = channelId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The channel the message was sent to.
     * </pre>
     *
     * <code>string channel_id = 1 [json_name = "channelId"];</code>
     * @param value The channelId to set.
     * @return This builder for chaining.
     */
    public Builder setChannelId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      channelId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The channel the message was sent to.
     * </pre>
     *
     * <code>string channel_id = 1 [json_name = "channelId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearChannelId() {
      channelId_ = getDefaultInstance().getChannelId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The channel the message was sent to.
     * </pre>
     *
     * <code>string channel_id = 1 [json_name = "channelId"];</code>
     * @param value The bytes for channelId to set.
     * @return This builder for chaining.
     */
    public Builder setChannelIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      channelId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object messageId_ = "";
    /**
     * <pre>
     * The unique ID assigned to the message.
     * </pre>
     *
     * <code>string message_id = 2 [json_name = "messageId"];</code>
     * @return The messageId.
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The unique ID assigned to the message.
     * </pre>
     *
     * <code>string message_id = 2 [json_name = "messageId"];</code>
     * @return The bytes for messageId.
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The unique ID assigned to the message.
     * </pre>
     *
     * <code>string message_id = 2 [json_name = "messageId"];</code>
     * @param value The messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      messageId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unique ID assigned to the message.
     * </pre>
     *
     * <code>string message_id = 2 [json_name = "messageId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageId() {
      messageId_ = getDefaultInstance().getMessageId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unique ID assigned to the message.
     * </pre>
     *
     * <code>string message_id = 2 [json_name = "messageId"];</code>
     * @param value The bytes for messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      messageId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.Int32Value code_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> codeBuilder_;
    /**
     * <pre>
     * The code representing a message type or category.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value code = 3 [json_name = "code"];</code>
     * @return Whether the code field is set.
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * The code representing a message type or category.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value code = 3 [json_name = "code"];</code>
     * @return The code.
     */
    public com.google.protobuf.Int32Value getCode() {
      if (codeBuilder_ == null) {
        return code_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : code_;
      } else {
        return codeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The code representing a message type or category.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value code = 3 [json_name = "code"];</code>
     */
    public Builder setCode(com.google.protobuf.Int32Value value) {
      if (codeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        code_ = value;
      } else {
        codeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The code representing a message type or category.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value code = 3 [json_name = "code"];</code>
     */
    public Builder setCode(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (codeBuilder_ == null) {
        code_ = builderForValue.build();
      } else {
        codeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The code representing a message type or category.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value code = 3 [json_name = "code"];</code>
     */
    public Builder mergeCode(com.google.protobuf.Int32Value value) {
      if (codeBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          code_ != null &&
          code_ != com.google.protobuf.Int32Value.getDefaultInstance()) {
          getCodeBuilder().mergeFrom(value);
        } else {
          code_ = value;
        }
      } else {
        codeBuilder_.mergeFrom(value);
      }
      if (code_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The code representing a message type or category.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value code = 3 [json_name = "code"];</code>
     */
    public Builder clearCode() {
      bitField0_ = (bitField0_ & ~0x00000004);
      code_ = null;
      if (codeBuilder_ != null) {
        codeBuilder_.dispose();
        codeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The code representing a message type or category.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value code = 3 [json_name = "code"];</code>
     */
    public com.google.protobuf.Int32Value.Builder getCodeBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getCodeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The code representing a message type or category.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value code = 3 [json_name = "code"];</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getCodeOrBuilder() {
      if (codeBuilder_ != null) {
        return codeBuilder_.getMessageOrBuilder();
      } else {
        return code_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : code_;
      }
    }
    /**
     * <pre>
     * The code representing a message type or category.
     * </pre>
     *
     * <code>.google.protobuf.Int32Value code = 3 [json_name = "code"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getCodeFieldBuilder() {
      if (codeBuilder_ == null) {
        codeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getCode(),
                getParentForChildren(),
                isClean());
        code_ = null;
      }
      return codeBuilder_;
    }

    private java.lang.Object username_ = "";
    /**
     * <pre>
     * Username of the message sender.
     * </pre>
     *
     * <code>string username = 4 [json_name = "username"];</code>
     * @return The username.
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Username of the message sender.
     * </pre>
     *
     * <code>string username = 4 [json_name = "username"];</code>
     * @return The bytes for username.
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Username of the message sender.
     * </pre>
     *
     * <code>string username = 4 [json_name = "username"];</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      username_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Username of the message sender.
     * </pre>
     *
     * <code>string username = 4 [json_name = "username"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      username_ = getDefaultInstance().getUsername();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Username of the message sender.
     * </pre>
     *
     * <code>string username = 4 [json_name = "username"];</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      username_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp createTime_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createTimeBuilder_;
    /**
     * <pre>
     * The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp create_time = 5 [json_name = "createTime"];</code>
     * @return Whether the createTime field is set.
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp create_time = 5 [json_name = "createTime"];</code>
     * @return The createTime.
     */
    public com.google.protobuf.Timestamp getCreateTime() {
      if (createTimeBuilder_ == null) {
        return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
      } else {
        return createTimeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp create_time = 5 [json_name = "createTime"];</code>
     */
    public Builder setCreateTime(com.google.protobuf.Timestamp value) {
      if (createTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createTime_ = value;
      } else {
        createTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp create_time = 5 [json_name = "createTime"];</code>
     */
    public Builder setCreateTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createTimeBuilder_ == null) {
        createTime_ = builderForValue.build();
      } else {
        createTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp create_time = 5 [json_name = "createTime"];</code>
     */
    public Builder mergeCreateTime(com.google.protobuf.Timestamp value) {
      if (createTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          createTime_ != null &&
          createTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getCreateTimeBuilder().mergeFrom(value);
        } else {
          createTime_ = value;
        }
      } else {
        createTimeBuilder_.mergeFrom(value);
      }
      if (createTime_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp create_time = 5 [json_name = "createTime"];</code>
     */
    public Builder clearCreateTime() {
      bitField0_ = (bitField0_ & ~0x00000010);
      createTime_ = null;
      if (createTimeBuilder_ != null) {
        createTimeBuilder_.dispose();
        createTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp create_time = 5 [json_name = "createTime"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreateTimeBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getCreateTimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp create_time = 5 [json_name = "createTime"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder() {
      if (createTimeBuilder_ != null) {
        return createTimeBuilder_.getMessageOrBuilder();
      } else {
        return createTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
      }
    }
    /**
     * <pre>
     * The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp create_time = 5 [json_name = "createTime"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreateTimeFieldBuilder() {
      if (createTimeBuilder_ == null) {
        createTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreateTime(),
                getParentForChildren(),
                isClean());
        createTime_ = null;
      }
      return createTimeBuilder_;
    }

    private com.google.protobuf.Timestamp updateTime_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updateTimeBuilder_;
    /**
     * <pre>
     * The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was last updated.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp update_time = 6 [json_name = "updateTime"];</code>
     * @return Whether the updateTime field is set.
     */
    public boolean hasUpdateTime() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was last updated.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp update_time = 6 [json_name = "updateTime"];</code>
     * @return The updateTime.
     */
    public com.google.protobuf.Timestamp getUpdateTime() {
      if (updateTimeBuilder_ == null) {
        return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
      } else {
        return updateTimeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was last updated.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp update_time = 6 [json_name = "updateTime"];</code>
     */
    public Builder setUpdateTime(com.google.protobuf.Timestamp value) {
      if (updateTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updateTime_ = value;
      } else {
        updateTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was last updated.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp update_time = 6 [json_name = "updateTime"];</code>
     */
    public Builder setUpdateTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (updateTimeBuilder_ == null) {
        updateTime_ = builderForValue.build();
      } else {
        updateTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was last updated.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp update_time = 6 [json_name = "updateTime"];</code>
     */
    public Builder mergeUpdateTime(com.google.protobuf.Timestamp value) {
      if (updateTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          updateTime_ != null &&
          updateTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getUpdateTimeBuilder().mergeFrom(value);
        } else {
          updateTime_ = value;
        }
      } else {
        updateTimeBuilder_.mergeFrom(value);
      }
      if (updateTime_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was last updated.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp update_time = 6 [json_name = "updateTime"];</code>
     */
    public Builder clearUpdateTime() {
      bitField0_ = (bitField0_ & ~0x00000020);
      updateTime_ = null;
      if (updateTimeBuilder_ != null) {
        updateTimeBuilder_.dispose();
        updateTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was last updated.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp update_time = 6 [json_name = "updateTime"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getUpdateTimeBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getUpdateTimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was last updated.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp update_time = 6 [json_name = "updateTime"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder() {
      if (updateTimeBuilder_ != null) {
        return updateTimeBuilder_.getMessageOrBuilder();
      } else {
        return updateTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
      }
    }
    /**
     * <pre>
     * The UNIX time (for gRPC clients) or ISO string (for REST clients) when the message was last updated.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp update_time = 6 [json_name = "updateTime"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getUpdateTimeFieldBuilder() {
      if (updateTimeBuilder_ == null) {
        updateTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getUpdateTime(),
                getParentForChildren(),
                isClean());
        updateTime_ = null;
      }
      return updateTimeBuilder_;
    }

    private com.google.protobuf.BoolValue persistent_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> persistentBuilder_;
    /**
     * <pre>
     * True if the message was persisted to the channel's history, false otherwise.
     * </pre>
     *
     * <code>.google.protobuf.BoolValue persistent = 7 [json_name = "persistent"];</code>
     * @return Whether the persistent field is set.
     */
    public boolean hasPersistent() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * True if the message was persisted to the channel's history, false otherwise.
     * </pre>
     *
     * <code>.google.protobuf.BoolValue persistent = 7 [json_name = "persistent"];</code>
     * @return The persistent.
     */
    public com.google.protobuf.BoolValue getPersistent() {
      if (persistentBuilder_ == null) {
        return persistent_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : persistent_;
      } else {
        return persistentBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * True if the message was persisted to the channel's history, false otherwise.
     * </pre>
     *
     * <code>.google.protobuf.BoolValue persistent = 7 [json_name = "persistent"];</code>
     */
    public Builder setPersistent(com.google.protobuf.BoolValue value) {
      if (persistentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        persistent_ = value;
      } else {
        persistentBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * True if the message was persisted to the channel's history, false otherwise.
     * </pre>
     *
     * <code>.google.protobuf.BoolValue persistent = 7 [json_name = "persistent"];</code>
     */
    public Builder setPersistent(
        com.google.protobuf.BoolValue.Builder builderForValue) {
      if (persistentBuilder_ == null) {
        persistent_ = builderForValue.build();
      } else {
        persistentBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * True if the message was persisted to the channel's history, false otherwise.
     * </pre>
     *
     * <code>.google.protobuf.BoolValue persistent = 7 [json_name = "persistent"];</code>
     */
    public Builder mergePersistent(com.google.protobuf.BoolValue value) {
      if (persistentBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          persistent_ != null &&
          persistent_ != com.google.protobuf.BoolValue.getDefaultInstance()) {
          getPersistentBuilder().mergeFrom(value);
        } else {
          persistent_ = value;
        }
      } else {
        persistentBuilder_.mergeFrom(value);
      }
      if (persistent_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * True if the message was persisted to the channel's history, false otherwise.
     * </pre>
     *
     * <code>.google.protobuf.BoolValue persistent = 7 [json_name = "persistent"];</code>
     */
    public Builder clearPersistent() {
      bitField0_ = (bitField0_ & ~0x00000040);
      persistent_ = null;
      if (persistentBuilder_ != null) {
        persistentBuilder_.dispose();
        persistentBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * True if the message was persisted to the channel's history, false otherwise.
     * </pre>
     *
     * <code>.google.protobuf.BoolValue persistent = 7 [json_name = "persistent"];</code>
     */
    public com.google.protobuf.BoolValue.Builder getPersistentBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getPersistentFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * True if the message was persisted to the channel's history, false otherwise.
     * </pre>
     *
     * <code>.google.protobuf.BoolValue persistent = 7 [json_name = "persistent"];</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getPersistentOrBuilder() {
      if (persistentBuilder_ != null) {
        return persistentBuilder_.getMessageOrBuilder();
      } else {
        return persistent_ == null ?
            com.google.protobuf.BoolValue.getDefaultInstance() : persistent_;
      }
    }
    /**
     * <pre>
     * True if the message was persisted to the channel's history, false otherwise.
     * </pre>
     *
     * <code>.google.protobuf.BoolValue persistent = 7 [json_name = "persistent"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
        getPersistentFieldBuilder() {
      if (persistentBuilder_ == null) {
        persistentBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                getPersistent(),
                getParentForChildren(),
                isClean());
        persistent_ = null;
      }
      return persistentBuilder_;
    }

    private java.lang.Object roomName_ = "";
    /**
     * <pre>
     * The name of the chat room, or an empty string if this message was not sent through a chat room.
     * </pre>
     *
     * <code>string room_name = 8 [json_name = "roomName"];</code>
     * @return The roomName.
     */
    public java.lang.String getRoomName() {
      java.lang.Object ref = roomName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The name of the chat room, or an empty string if this message was not sent through a chat room.
     * </pre>
     *
     * <code>string room_name = 8 [json_name = "roomName"];</code>
     * @return The bytes for roomName.
     */
    public com.google.protobuf.ByteString
        getRoomNameBytes() {
      java.lang.Object ref = roomName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The name of the chat room, or an empty string if this message was not sent through a chat room.
     * </pre>
     *
     * <code>string room_name = 8 [json_name = "roomName"];</code>
     * @param value The roomName to set.
     * @return This builder for chaining.
     */
    public Builder setRoomName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      roomName_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name of the chat room, or an empty string if this message was not sent through a chat room.
     * </pre>
     *
     * <code>string room_name = 8 [json_name = "roomName"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRoomName() {
      roomName_ = getDefaultInstance().getRoomName();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name of the chat room, or an empty string if this message was not sent through a chat room.
     * </pre>
     *
     * <code>string room_name = 8 [json_name = "roomName"];</code>
     * @param value The bytes for roomName to set.
     * @return This builder for chaining.
     */
    public Builder setRoomNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      roomName_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object groupId_ = "";
    /**
     * <pre>
     * The ID of the group, or an empty string if this message was not sent through a group channel.
     * </pre>
     *
     * <code>string group_id = 9 [json_name = "groupId"];</code>
     * @return The groupId.
     */
    public java.lang.String getGroupId() {
      java.lang.Object ref = groupId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The ID of the group, or an empty string if this message was not sent through a group channel.
     * </pre>
     *
     * <code>string group_id = 9 [json_name = "groupId"];</code>
     * @return The bytes for groupId.
     */
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      java.lang.Object ref = groupId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The ID of the group, or an empty string if this message was not sent through a group channel.
     * </pre>
     *
     * <code>string group_id = 9 [json_name = "groupId"];</code>
     * @param value The groupId to set.
     * @return This builder for chaining.
     */
    public Builder setGroupId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      groupId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the group, or an empty string if this message was not sent through a group channel.
     * </pre>
     *
     * <code>string group_id = 9 [json_name = "groupId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupId() {
      groupId_ = getDefaultInstance().getGroupId();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the group, or an empty string if this message was not sent through a group channel.
     * </pre>
     *
     * <code>string group_id = 9 [json_name = "groupId"];</code>
     * @param value The bytes for groupId to set.
     * @return This builder for chaining.
     */
    public Builder setGroupIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      groupId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object userIdOne_ = "";
    /**
     * <pre>
     * The ID of the first DM user, or an empty string if this message was not sent through a DM chat.
     * </pre>
     *
     * <code>string user_id_one = 10 [json_name = "userIdOne"];</code>
     * @return The userIdOne.
     */
    public java.lang.String getUserIdOne() {
      java.lang.Object ref = userIdOne_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userIdOne_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The ID of the first DM user, or an empty string if this message was not sent through a DM chat.
     * </pre>
     *
     * <code>string user_id_one = 10 [json_name = "userIdOne"];</code>
     * @return The bytes for userIdOne.
     */
    public com.google.protobuf.ByteString
        getUserIdOneBytes() {
      java.lang.Object ref = userIdOne_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userIdOne_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The ID of the first DM user, or an empty string if this message was not sent through a DM chat.
     * </pre>
     *
     * <code>string user_id_one = 10 [json_name = "userIdOne"];</code>
     * @param value The userIdOne to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdOne(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userIdOne_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the first DM user, or an empty string if this message was not sent through a DM chat.
     * </pre>
     *
     * <code>string user_id_one = 10 [json_name = "userIdOne"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUserIdOne() {
      userIdOne_ = getDefaultInstance().getUserIdOne();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the first DM user, or an empty string if this message was not sent through a DM chat.
     * </pre>
     *
     * <code>string user_id_one = 10 [json_name = "userIdOne"];</code>
     * @param value The bytes for userIdOne to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdOneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userIdOne_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private java.lang.Object userIdTwo_ = "";
    /**
     * <pre>
     * The ID of the second DM user, or an empty string if this message was not sent through a DM chat.
     * </pre>
     *
     * <code>string user_id_two = 11 [json_name = "userIdTwo"];</code>
     * @return The userIdTwo.
     */
    public java.lang.String getUserIdTwo() {
      java.lang.Object ref = userIdTwo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userIdTwo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The ID of the second DM user, or an empty string if this message was not sent through a DM chat.
     * </pre>
     *
     * <code>string user_id_two = 11 [json_name = "userIdTwo"];</code>
     * @return The bytes for userIdTwo.
     */
    public com.google.protobuf.ByteString
        getUserIdTwoBytes() {
      java.lang.Object ref = userIdTwo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userIdTwo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The ID of the second DM user, or an empty string if this message was not sent through a DM chat.
     * </pre>
     *
     * <code>string user_id_two = 11 [json_name = "userIdTwo"];</code>
     * @param value The userIdTwo to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdTwo(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userIdTwo_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the second DM user, or an empty string if this message was not sent through a DM chat.
     * </pre>
     *
     * <code>string user_id_two = 11 [json_name = "userIdTwo"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUserIdTwo() {
      userIdTwo_ = getDefaultInstance().getUserIdTwo();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the second DM user, or an empty string if this message was not sent through a DM chat.
     * </pre>
     *
     * <code>string user_id_two = 11 [json_name = "userIdTwo"];</code>
     * @param value The bytes for userIdTwo to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdTwoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userIdTwo_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:nakama.realtime.ChannelMessageAck)
  }

  // @@protoc_insertion_point(class_scope:nakama.realtime.ChannelMessageAck)
  private static final com.heroiclabs.nakama.rtapi.ChannelMessageAck DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.heroiclabs.nakama.rtapi.ChannelMessageAck();
  }

  public static com.heroiclabs.nakama.rtapi.ChannelMessageAck getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChannelMessageAck>
      PARSER = new com.google.protobuf.AbstractParser<ChannelMessageAck>() {
    @java.lang.Override
    public ChannelMessageAck parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ChannelMessageAck> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChannelMessageAck> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.heroiclabs.nakama.rtapi.ChannelMessageAck getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

