// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/heroiclabs/nakama-common/rtapi/realtime.proto
// Protobuf Java Version: 4.28.2

package com.heroiclabs.nakama.rtapi;

public interface ErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nakama.realtime.Error)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The error code which should be one of "Error.Code" enums.
   * </pre>
   *
   * <code>int32 code = 1 [json_name = "code"];</code>
   * @return The code.
   */
  int getCode();

  /**
   * <pre>
   * A message in English to help developers debug the response.
   * </pre>
   *
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * A message in English to help developers debug the response.
   * </pre>
   *
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * Additional error details which may be different for each response.
   * </pre>
   *
   * <code>map&lt;string, string&gt; context = 3 [json_name = "context"];</code>
   */
  int getContextCount();
  /**
   * <pre>
   * Additional error details which may be different for each response.
   * </pre>
   *
   * <code>map&lt;string, string&gt; context = 3 [json_name = "context"];</code>
   */
  boolean containsContext(
      java.lang.String key);
  /**
   * Use {@link #getContextMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getContext();
  /**
   * <pre>
   * Additional error details which may be different for each response.
   * </pre>
   *
   * <code>map&lt;string, string&gt; context = 3 [json_name = "context"];</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getContextMap();
  /**
   * <pre>
   * Additional error details which may be different for each response.
   * </pre>
   *
   * <code>map&lt;string, string&gt; context = 3 [json_name = "context"];</code>
   */
  /* nullable */
java.lang.String getContextOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * Additional error details which may be different for each response.
   * </pre>
   *
   * <code>map&lt;string, string&gt; context = 3 [json_name = "context"];</code>
   */
  java.lang.String getContextOrThrow(
      java.lang.String key);
}
