// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/heroiclabs/nakama-common/rtapi/realtime.proto
// Protobuf Java Version: 4.28.2

package com.heroiclabs.nakama.rtapi;

public interface StatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nakama.realtime.Status)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * User statuses.
   * </pre>
   *
   * <code>repeated .nakama.realtime.UserPresence presences = 1 [json_name = "presences"];</code>
   */
  java.util.List<com.heroiclabs.nakama.rtapi.UserPresence> 
      getPresencesList();
  /**
   * <pre>
   * User statuses.
   * </pre>
   *
   * <code>repeated .nakama.realtime.UserPresence presences = 1 [json_name = "presences"];</code>
   */
  com.heroiclabs.nakama.rtapi.UserPresence getPresences(int index);
  /**
   * <pre>
   * User statuses.
   * </pre>
   *
   * <code>repeated .nakama.realtime.UserPresence presences = 1 [json_name = "presences"];</code>
   */
  int getPresencesCount();
  /**
   * <pre>
   * User statuses.
   * </pre>
   *
   * <code>repeated .nakama.realtime.UserPresence presences = 1 [json_name = "presences"];</code>
   */
  java.util.List<? extends com.heroiclabs.nakama.rtapi.UserPresenceOrBuilder> 
      getPresencesOrBuilderList();
  /**
   * <pre>
   * User statuses.
   * </pre>
   *
   * <code>repeated .nakama.realtime.UserPresence presences = 1 [json_name = "presences"];</code>
   */
  com.heroiclabs.nakama.rtapi.UserPresenceOrBuilder getPresencesOrBuilder(
      int index);
}
